package com.tnc.tnc.life.routes;
import net.minecraft.core.*;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.*;
/** Atomic real-material processing, with output space checked before charging. */
public final class RouteWork {
    public static void tick(ServerLevel l,RouteNodeEntity node){switch(node.kind()){
        case PAPER_PRESS->{if(hasWater(l,node)){var s=node.inventory.getItem(0);if(s.is(RouteContent.item("tide_reed_stem")))process(node,s.getItem(),2,Items.PAPER,3,16,4);else process(node,Items.SUGAR_CANE,2,Items.PAPER,3,16,4);}else node.status="纸皮压机需要相邻清水";}
        case SAWMILL->{var input=node.inventory.getItem(0);if(input.is(net.minecraft.tags.ItemTags.LOGS)){var id=net.minecraftforge.registries.ForgeRegistries.ITEMS.getKey(input.getItem());var planks=net.minecraftforge.registries.ForgeRegistries.ITEMS.getValue(net.minecraft.resources.ResourceLocation.fromNamespaceAndPath(id.getNamespace(),id.getPath().replace("_log","_planks").replace("_wood","_planks").replace("stripped_","")));if(planks!=null&&planks!=Items.AIR)process(node,input.getItem(),1,planks,6,12,4);}}
        case LOOM->{var s=node.inventory.getItem(0);if(s.is(RouteContent.item("sail_fiber")))process(node,s.getItem(),2,RouteContent.item("mist_cloth"),1,30,6);else process(node,RouteContent.item("mist_cotton_fiber"),2,RouteContent.item("mist_cloth"),1,30,6);}
        case DRYER->{var input=node.inventory.getItem(0);if(input.isEdible()&&!input.is(RouteContent.item("packed_meal"))&&input.getItem().getFoodProperties()!=null&&input.getItem().getFoodProperties().getNutrition()>=6&&node.inventory.getItem(1).is(Items.PAPER))process(node,input.getItem(),1,RouteContent.item("packed_meal"),1,24,6);}
        case IRRIGATOR->irrigate(l,node);
        case HARVESTER->harvest(l,node);
        case FEED_PLATE->feed(l,node);
        case SEED_SORTER->sort(node);
        case ALARM->{if(!l.getEntitiesOfClass(net.minecraft.world.entity.monster.Monster.class,new net.minecraft.world.phys.AABB(node.getBlockPos()).inflate(9),net.minecraft.world.entity.Entity::isAlive).isEmpty()&&l.getGameTime()%100==0&&node.spend(2)){l.playSound(null,node.getBlockPos(),net.minecraft.sounds.SoundEvents.BELL_BLOCK,net.minecraft.sounds.SoundSource.BLOCKS,.6f,1.2f);node.getPersistentData().putLong("AlarmUntil",l.getGameTime()+40);node.status="守望铃：九格内有敌意生物";}}
        case INCUBATOR->{var egg=node.inventory.getItem(0);if(egg.is(RouteContent.item("fertile_pasture_egg"))&&egg.hasTag()&&egg.getTag().hasUUID("EggOwner")&&node.owner.equals(egg.getTag().getUUID("EggOwner"))){var t=egg.getOrCreateTag();boolean powered=node.upkeep(.15);t.putInt("Incubation",Math.min(48000,Math.max(0,t.getInt("Incubation"))+(powered?25:20)));node.status=powered?"暖育中 · 加快25%":"基础孵育中 · 等待供魔";if(t.getInt("Incubation")>=48000&&RouteHatching.hatch(l,node.getBlockPos(),node.owner,egg)){egg.shrink(1);node.status="幼兽已出生，消耗一枚实际受精卵";}}}
        case CART_TRACK->cart(l,node);
        default->{}
    }}
    private static void process(RouteNodeEntity n,Item input,int needed,Item output,int count,int cost,int seconds){if(input==null||output==null)return;var source=n.inventory.getItem(0);var target=n.inventory.getItem(4);if(!source.is(input)||source.getCount()<needed||!target.isEmpty()&&(!target.is(output)||target.getCount()+count>target.getMaxStackSize())){n.status="等待材料或成品空间";return;}if(n.kind()==RouteKind.DRYER&&!n.inventory.getItem(1).is(Items.PAPER))return;
        String id=net.minecraftforge.registries.ForgeRegistries.ITEMS.getKey(output).toString();if(!id.equals(n.job)){n.progress=0;n.job=id;}if(n.mana<cost){n.status="需要 "+cost+" 魔力";return;}n.progress++;n.status="加工 "+n.progress+"/"+seconds+" 秒";if(n.progress<seconds)return;if(!n.spend(cost))return;source.shrink(needed);if(n.kind()==RouteKind.DRYER)n.inventory.getItem(1).shrink(1);if(target.isEmpty())n.inventory.setItem(4,new ItemStack(output,count));else target.grow(count);RouteProgress.awardOwner((ServerLevel)n.getLevel(),n.owner,"network/worked");n.progress=0;n.job="";}
    private static void irrigate(ServerLevel l,RouteNodeEntity n){if(l.getGameTime()%200!=0||n.mana<8)return;boolean changed=false;for(BlockPos p:BlockPos.betweenClosed(n.getBlockPos().offset(-4,-1,-4),n.getBlockPos().offset(4,0,4))){if(RouteAccess.allowed(l,p,n.owner)&&l.getBlockState(p).is(Blocks.FARMLAND)&&l.getBlockState(p).getValue(FarmBlock.MOISTURE)<7){l.setBlock(p,l.getBlockState(p).setValue(FarmBlock.MOISTURE,7),3);changed=true;}}if(changed)n.spend(8);n.status="只轻灌传统耕地；魔植需流动魔力";}
    private static void harvest(ServerLevel l,RouteNodeEntity n){if(n.mana<4)return;for(BlockPos p:BlockPos.betweenClosed(n.getBlockPos().offset(-4,0,-4),n.getBlockPos().offset(4,1,4))){if(!RouteAccess.allowed(l,p,n.owner))continue;var s=l.getBlockState(p);if(s.getBlock() instanceof CropBlock crop&&crop.isMaxAge(s)){var drops=Block.getDrops(s,l,p,l.getBlockEntity(p));Item seed=crop.getCloneItemStack(l,p,s).getItem();boolean replant=false;for(var drop:drops)if(drop.is(seed)&&drop.getCount()>0){drop.shrink(1);replant=true;break;}if(!replant)continue;var outputs=simulateOutputs(n,drops);if(outputs==null)return;if(!n.spend(4))return;n.inventory.setItem(4,outputs[0]);n.inventory.setItem(5,outputs[1]);l.setBlock(p,crop.getStateForAge(0),3);n.status="已采收并扣除一份种源补种";return;}}}
    private static boolean hasWater(ServerLevel l,RouteNodeEntity n){for(var d:Direction.values()){var p=n.getBlockPos().relative(d);if(l.hasChunkAt(p)&&l.getFluidState(p).is(net.minecraft.tags.FluidTags.WATER))return true;}return false;}
    static ItemStack[] simulateOutputs(RouteNodeEntity n,java.util.List<ItemStack> drops){var out=new ItemStack[]{n.inventory.getItem(4).copy(),n.inventory.getItem(5).copy()};for(var drop:drops){var remaining=drop.copy();for(int i=0;i<2&&!remaining.isEmpty();i++){if(!out[i].isEmpty()&&!ItemStack.isSameItemSameTags(out[i],remaining))continue;int fit=Math.min(remaining.getCount(),remaining.getMaxStackSize()-out[i].getCount());if(fit<=0)continue;if(out[i].isEmpty())out[i]=remaining.copyWithCount(fit);else out[i].grow(fit);remaining.shrink(fit);}if(!remaining.isEmpty())return null;}return out;}
    private static boolean canStore(RouteNodeEntity n,ItemStack s){var out=n.inventory.getItem(4);return out.isEmpty()||ItemStack.isSameItemSameTags(out,s)&&out.getCount()+s.getCount()<=out.getMaxStackSize();}
    private static void store(RouteNodeEntity n,ItemStack s){var out=n.inventory.getItem(4);if(out.isEmpty())n.inventory.setItem(4,s.copy());else out.grow(s.getCount());}
    private static void feed(ServerLevel l,RouteNodeEntity n){var stack=n.inventory.getItem(0);if(stack.isEmpty()||n.mana<1)return;for(var d:Direction.values()){var p=n.getBlockPos().relative(d);if(RouteAccess.allowed(l,p,n.owner)&&l.getBlockEntity(p) instanceof com.tnc.tnc.life.pasture.PastureFacilityEntity tray&&n.owner.equals(tray.owner())){var offered=stack.copyWithCount(Math.min(8,stack.getCount()));int got=offered.getCount()-tray.insert(offered).getCount();if(got>0){stack.shrink(got);n.spend(1);n.status="已分配 "+got+" 份实际饲料";return;}}}}
    private static void sort(RouteNodeEntity n){var stack=n.inventory.getItem(0);if(stack.isEmpty())return;String id=net.minecraftforge.registries.ForgeRegistries.ITEMS.getKey(stack.getItem()).getPath();if((id.endsWith("_seeds")||id.endsWith("_seed"))&&canStore(n,stack)&&n.spend(5)){store(n,stack);n.inventory.setItem(0,ItemStack.EMPTY);n.status="种源已经分拣到成品格";}}
    private static void cart(ServerLevel l,RouteNodeEntity n){for(var cart:l.getEntitiesOfClass(net.minecraft.world.entity.vehicle.MinecartChest.class,new net.minecraft.world.phys.AABB(n.getBlockPos()).inflate(1.5))){if(cart.isEmpty()||!RouteAccess.allowed(l,cart.blockPosition(),n.owner))continue;var d=cart.getPersistentData();if(d.hasUUID("ManaTrackOwner")&&!n.owner.equals(d.getUUID("ManaTrackOwner")))continue;long now=l.getGameTime();if(d.getLong("ManaTrackTick")==now)continue;boolean consecutive=now-d.getLong("ManaTrackTick")<=40&&d.hasUUID("ManaTrackOwner");double moved=consecutive?Math.min(10,cart.position().distanceTo(new net.minecraft.world.phys.Vec3(d.getDouble("ManaCartX"),d.getDouble("ManaCartY"),d.getDouble("ManaCartZ")))):0;double distance=d.getDouble("ManaTrackDistance")+moved;int due=(int)(distance/10);if(n.mana<Math.max(1,due)){cart.setDeltaMovement(net.minecraft.world.phys.Vec3.ZERO);n.status="运货暂停：需要魔力";continue;}if(due>0)n.spend(due);d.putUUID("ManaTrackOwner",n.owner);d.putLong("ManaTrackTick",now);d.putDouble("ManaTrackDistance",distance-due*10);d.putDouble("ManaCartX",cart.getX());d.putDouble("ManaCartY",cart.getY());d.putDouble("ManaCartZ",cart.getZ());var direction=cart.getDeltaMovement().normalize();if(direction.lengthSqr()>.1)cart.setDeltaMovement(direction.scale(.25));n.status="实际货车行进每十格耗1魔力；沿铁轨铺设";}}
}
