package com.tnc.tnc.life.routes;
import java.util.*;
public final class RouteBooks {
    public static List<String> pages(String id){var pages=new ArrayList<String>();switch(id){
        case "season_handbook"->{pages.add("四时农圃\n\n每季七日，一年二十八日。应季正常长，相邻季六成，反季四分之一。换季不会杀死作物。睡觉推进农历，成长只累计真实运行时间。\n\n厨房配方请用 JEI 查看当前配方。");pages.add("春：绿叶、根菜、嫩莓。\n夏：水稻、瓜果、热带果。\n秋：谷物、葡萄、果园。\n冬：根菜、卷心菜、冰葡萄。\n\n菌菇、水生与异境植物保持原种法。护候灯在封闭温室中恢复应季速度。");}
        case "magic_garden_book"->{pages.add("魔植花园\n\n野外成熟果实可直接种；纤维作物挖根得种与产物；多年生株拿普通剪刀取芽。无需采样夹。\n\n土源：八泥土＋一满魔力瓶。十秒转同层九乘九泥土。流动魔力灌溉八格。缺灌溉只暂停，不死亡。");for(var s:com.tnc.tnc.life.botanical.BotanicalSpecies.values())pages.add(s.name+"\n\n"+s.help+"\n\n产物："+s.productName+"。人工栽培需魔法土和流动魔力。种子可保留，也可交易。");for(var s:NewPlantKind.values())pages.add(s.name+"\n\n"+s.help+"。\n\n产物："+s.productName+"。成长不挑群系，特殊条件只控制供魔。");}
        case "beast_ranch_book"->{pages.add("异兽牧场\n\n先喂喜食取得短暂信任，再持笼长按捕获。灵纹、曜纹、星髓三级分别需要三、五、八秒。\n\n牧务杖选兽，右键栖居标记设窝。地面九乘九，飞行九乘九乘九。再喂食照料建立归属，食槽提供实际饲料。");for(var s:com.tnc.tnc.life.pasture.PastureSpecies.ALL)pages.add(s.name()+"\n\n喜食："+new net.minecraft.world.item.ItemStack(s.food()).getHoverName().getString()+"\n产物："+s.product()+"\n笼级："+com.tnc.tnc.life.pasture.PastureCageItem.tierFor(s.id())+"\n\n取产与工作共享资源和食物，停工不会饿死。具体状态空手右键查看。");}
        default->{pages.add("魔导工坊\n\n注能台：放瓶或桶，点击注能，每秒扣自身五点魔力。瓶一百，精炼瓶四百，桶四百。\n\n集露盏接植物三乘三乘三范围。集息器只绑定一兽。魔力不能从流体渠抽取，也不会转成五倍电力。");pages.add("三级线路：8 / 32 / 128魔力每秒。共享同根线时合计限流。\n储池：1000 / 8000 / 32000。\n折光镜：12格，远折镜24格，沿六个轴对齐。\n分流阀潜行右键换优先。检流尺查看瓶颈。\n\n只在加载区运行，不补算离线魔力。");for(var k:RouteKind.values())if(!k.wire())pages.add(k.name+"\n\n储量 "+k.capacity+"\n带宽 "+k.rate+" 魔力/秒。\n\n右键打开工作面板；材料放左侧，成品从中间取。手持检流尺右键读工作状态。所属权限改变会停止运作。");pages.add("饰品充能台\n\n放入归途缎带、缓降羽饰、探矿耳坠、守露护符或魔道机甲。接入纯魔力网络后每秒最多充16，不超过物品容量。\n\n副手饰品才生效；机甲右键穿戴。法术机枪消耗真实箭和机甲魔力，不破坏地形。");}
    }return catalogue(id,pages);}
    private static List<String> catalogue(String id,List<String> fallback){try(var stream=RouteBooks.class.getResourceAsStream("/data/tnc/life_routes/catalogue.json")){var root=com.google.gson.JsonParser.parseReader(new java.io.InputStreamReader(java.util.Objects.requireNonNull(stream),java.nio.charset.StandardCharsets.UTF_8)).getAsJsonObject();var out=new ArrayList<String>();out.add(fallback.get(0));if(fallback.size()>1)out.add(fallback.get(1));if(id.equals("mana_workshop_book"))out.add(fallback.get(fallback.size()-1));String category=switch(id){case "season_handbook"->"traditional";case "magic_garden_book"->"magic";case "beast_ranch_book"->"animals";default->"machines";};for(var raw:root.getAsJsonArray(category)){var e=raw.getAsJsonObject();String name=e.get("name").getAsString();String text=name+"\n\n";if(category.equals("traditional")){text+="适种："+e.get("seasons").getAsString()+"\n种源："+e.get("item").getAsString()+"\n\n"+e.get("use").getAsString()+"\n原模组配方例："+(e.has("recipes")?e.get("recipes").toString():"无")+"。以JEI当前启用配方为准。";}else if(category.equals("magic")){text+=e.get("help").getAsString()+"\n\n种源："+e.get("seed").getAsString()+"\n产物："+e.get("product").getAsString()+"\n用途："+e.get("use").getAsString();}else if(category.equals("animals")){text+="喜食："+e.get("food").getAsString()+"\n产物："+e.get("product").getAsString()+"\n栖居："+e.get("habitat").getAsString()+"\n笼级："+com.tnc.tnc.life.pasture.PastureCageItem.tierFor(e.get("id").getAsString());}else{text+=e.get("help").getAsString();}while(text.length()>225){out.add(text.substring(0,225));text=text.substring(225);}out.add(text);}return out;}catch(java.io.IOException|RuntimeException e){return fallback;}}
}
