package com.tnc.tnc.life.routes;
import com.tnc.tnc.adventure.AdventureGameTests;
import com.tnc.tnc.life.pasture.*;
import net.minecraft.core.*;
import net.minecraft.gametest.framework.*;
import net.minecraft.world.inventory.*;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.*;
import net.minecraftforge.gametest.*;
@GameTestHolder("tncroute") @PrefixGameTestTemplate(false)
public final class RouteGameTests {
    @GameTest(template="empty",timeoutTicks=100) public static void heldCaptureAndCopiedCageReleaseOnlyOnce(GameTestHelper h){var p=AdventureGameTests.player(h);p.setGameMode(net.minecraft.world.level.GameType.CREATIVE);p.moveTo(h.absolutePos(new BlockPos(2,2,2)),0,0);var a=PastureRegistry.TYPES.get("starfelt_hare").create(h.getLevel());a.setNoAi(true);a.moveTo(h.absolutePos(new BlockPos(3,2,2)),0,0);h.getLevel().addFreshEntity(a);var cage=new ItemStack(RouteContent.item("pasture_cage"));p.getInventory().setItem(0,cage);p.getInventory().selected=0;var item=(PastureCageItem)cage.getItem();h.assertTrue(item.capture(p,cage,a).consumesAction(),"capture starts with correct cage");h.runAfterDelay(61,()->{item.onUseTick(h.getLevel(),p,cage,139);h.assertTrue(a.isRemoved()&&cage.hasTag()&&cage.getTag().hasUUID("Ticket"),"held capture seals actual animal after three seconds");var copy=cage.copy();var target=h.absolutePos(new BlockPos(4,1,4));h.getLevel().setBlock(target,Blocks.STONE.defaultBlockState(),3);var hit=new net.minecraft.world.phys.BlockHitResult(net.minecraft.world.phys.Vec3.atCenterOf(target),Direction.UP,target,false);var context=new net.minecraft.world.item.context.UseOnContext(p,net.minecraft.world.InteractionHand.MAIN_HAND,hit);h.assertTrue(item.useOn(context).consumesAction(),"first release succeeds");p.getInventory().setItem(0,copy);h.assertTrue(!item.useOn(context).consumesAction(),"copied cage cannot release same ticket again");h.succeed();});}
    @GameTest(template="empty",timeoutTicks=40) public static void storageReserveIsRetained(GameTestHelper h){var owner=AdventureGameTests.player(h).getUUID();var source=node(h,RouteKind.POOL,new BlockPos(1,2,1),owner);var sink=node(h,RouteKind.SAWMILL,new BlockPos(2,2,1),owner);source.mana=254;source.reserve=250;RouteNetwork.add(h.getLevel(),source.getBlockPos());RouteNetwork.add(h.getLevel(),sink.getBlockPos());RouteNetwork.tickNetwork(h.getLevel());h.assertTrue(source.mana==250&&sink.mana==4,"only surplus over the retained quota is distributed");h.succeed();}
    @GameTest(template="empty",timeoutTicks=40) public static void buildingRulerPlacesFiveUsingRealMaterials(GameTestHelper h){var p=AdventureGameTests.player(h);p.setGameMode(net.minecraft.world.level.GameType.SURVIVAL);var anchor=h.absolutePos(new BlockPos(2,2,2));h.getLevel().setBlock(anchor,Blocks.STONE.defaultBlockState(),3);p.moveTo(anchor.getX()+.5,anchor.getY()+2,anchor.getZ()+.5,0,0);var ruler=new ItemStack(RouteContent.item("mana_building_ruler"));p.getInventory().setItem(0,ruler);p.getInventory().setItem(1,new ItemStack(Items.STONE,5));p.getInventory().selected=0;RouteChargeLedger.get(h.getLevel()).deposit(ruler,600,30);var context=new net.minecraft.world.item.context.UseOnContext(p,net.minecraft.world.InteractionHand.MAIN_HAND,new net.minecraft.world.phys.BlockHitResult(net.minecraft.world.phys.Vec3.atCenterOf(anchor),Direction.UP,anchor,false));((RouteAccessory)ruler.getItem()).useOn(context);int placed=0;for(int i=0;i<5;i++)if(h.getLevel().getBlockState(anchor.above().relative(p.getDirection(),i)).is(Blocks.STONE))placed++;h.assertTrue(placed==5&&p.getInventory().getItem(1).isEmpty()&&RouteChargeLedger.get(h.getLevel()).amount(ruler)==15,"five blocks, five actual materials, fifteen mana");h.succeed();}
    @GameTest(template="empty",timeoutTicks=40) public static void filledBottleMovesToOutputWithoutCopying(GameTestHelper h){var p=AdventureGameTests.player(h);var n=node(h,RouteKind.INFUSER,new BlockPos(2,2,2),p.getUUID());var bottle=new ItemStack(PastureRegistry.item("mana_bottle"));PastureBottleLedger.get(h.getLevel()).deposit(bottle,100,92);n.inventory.setItem(0,bottle);n.mana=30;RouteNodeEntity.operate(h.getLevel(),n);var output=n.inventory.getItem(4);h.assertTrue(n.mana==22&&n.inventory.getItem(0).isEmpty()&&PastureBottleLedger.get(h.getLevel()).amount(output)==100,"refilling transfers the same identity and eight actual mana");h.assertTrue(PastureBottleLedger.get(h.getLevel()).withdraw(output,100)==100&&PastureBottleLedger.get(h.getLevel()).withdraw(output.copy(),100)==0,"copy cannot spend a full bottle twice");h.succeed();}
    @GameTest(template="empty",timeoutTicks=40) public static void incubatorUsesOwnedRealEggAndFractionalMana(GameTestHelper h){var p=AdventureGameTests.player(h);var n=node(h,RouteKind.INCUBATOR,new BlockPos(2,2,2),p.getUUID());var egg=new ItemStack(RouteContent.item("fertile_pasture_egg"));egg.getOrCreateTag().putUUID("EggOwner",p.getUUID());egg.getOrCreateTag().putString("Species","mirrorwing_moth");n.inventory.setItem(0,egg);n.mana=10;for(int i=0;i<20;i++)RouteNodeEntity.operate(h.getLevel(),n);h.assertTrue(n.mana==7&&egg.getTag().getInt("Incubation")==500,"twenty seconds use three mana and advance twenty-five ticks each");h.assertTrue(egg.getCount()==1,"partial incubation never creates or consumes an egg");egg.getOrCreateTag().putUUID("EggOwner",java.util.UUID.randomUUID());RouteNodeEntity.operate(h.getLevel(),n);h.assertTrue(n.mana==7&&egg.getTag().getInt("Incubation")==500,"foreign egg cannot be processed");h.succeed();}
    @GameTest(template="empty",timeoutTicks=40) public static void chargerDoesNotChargeGunModule(GameTestHelper h){var p=AdventureGameTests.player(h);var n=node(h,RouteKind.CHARGER,new BlockPos(2,2,2),p.getUUID());var gun=new ItemStack(RouteContent.item("mech_spellgun"));n.inventory.setItem(0,gun);n.mana=50;RouteNodeEntity.operate(h.getLevel(),n);h.assertTrue(n.mana==50&&RouteChargeLedger.get(h.getLevel()).amount(gun)==0,"module runs on worn mech rather than a useless hidden battery");h.succeed();}
    private static RouteNodeEntity node(GameTestHelper h,RouteKind kind,BlockPos local,java.util.UUID owner){var p=h.absolutePos(local);h.getLevel().setBlock(p,RouteContent.NODES.get(kind.id).get().defaultBlockState(),3);var n=(RouteNodeEntity)h.getLevel().getBlockEntity(p);n.owner=owner;return n;}
    private static ItemStack full(GameTestHelper h){var b=new ItemStack(PastureRegistry.item("mana_bottle"));PastureBottleLedger.get(h.getLevel()).deposit(b,100,100);return b;}
    private static CraftingMenu crafting(GameTestHelper h,net.minecraft.server.level.ServerPlayer p,ItemStack b){var menu=new CraftingMenu(1,p.getInventory(),ContainerLevelAccess.create(h.getLevel(),h.absolutePos(new BlockPos(2,1,2))));for(int i=1;i<=9;i++)menu.getSlot(i).set(i==5?b:new ItemStack(Items.DIRT,2));p.containerMenu=menu;menu.slotsChanged(menu.getSlot(1).container);return menu;}
    @GameTest(template="empty",timeoutTicks=40) public static void normalTakeDebitsAndReturnsBottle(GameTestHelper h){var p=AdventureGameTests.player(h);var bottle=full(h);var menu=crafting(h,p,bottle);h.assertTrue(menu.getSlot(0).hasItem(),"full bottle produces soil source");menu.clicked(0,0,ClickType.PICKUP,p);h.assertTrue(menu.getCarried().is(RouteContent.SOIL_SOURCE.get().asItem()),"pickup gets actual source");h.assertTrue(PastureBottleLedger.get(h.getLevel()).amount(bottle)==0,"one real 100M debit");h.assertTrue(menu.getSlot(5).getItem().getItem() instanceof ManaBottleItem,"empty bottle remains");h.assertTrue(menu.getSlot(0).getItem().isEmpty(),"stale recipe disappears");h.succeed();}
    @GameTest(template="empty",timeoutTicks=40) public static void shiftTakeCannotCraftTwice(GameTestHelper h){var p=AdventureGameTests.player(h);var bottle=full(h);var menu=crafting(h,p,bottle);menu.clicked(0,0,ClickType.QUICK_MOVE,p);h.assertTrue(PastureBottleLedger.get(h.getLevel()).amount(bottle)==0,"shift debits even after result count becomes zero");int count=0;for(var s:p.getInventory().items)if(s.is(RouteContent.SOIL_SOURCE.get().asItem()))count+=s.getCount();h.assertTrue(count==1,"stacked dirt cannot create another source from empty bottle");h.succeed();}
    @GameTest(template="empty",timeoutTicks=40) public static void clonedBottlesCannotMerge(GameTestHelper h){var p=AdventureGameTests.player(h);var menu=new CraftingMenu(1,p.getInventory(),ContainerLevelAccess.create(h.getLevel(),h.absolutePos(new BlockPos(2,1,2))));var bottle=full(h);for(int i=1;i<=4;i++)menu.getSlot(i).set(bottle.copy());menu.getSlot(5).set(new ItemStack(Items.BUCKET));menu.slotsChanged(menu.getSlot(1).container);h.assertTrue(menu.getSlot(0).getItem().isEmpty(),"one ledger copied four times is not 400 mana");h.succeed();}
    @GameTest(template="empty",timeoutTicks=40) public static void chargerConservesMana(GameTestHelper h){var p=AdventureGameTests.player(h);var n=node(h,RouteKind.CHARGER,new BlockPos(2,2,2),p.getUUID());var s=new ItemStack(RouteContent.item("dew_ward_charm"));n.inventory.setItem(0,s);n.mana=50;RouteNodeEntity.operate(h.getLevel(),n);h.assertTrue(n.mana==34&&RouteChargeLedger.get(h.getLevel()).amount(s)==16,"16 in equals 16 out");RouteChargeLedger.get(h.getLevel()).deposit(s,300,300);RouteNodeEntity.operate(h.getLevel(),n);h.assertTrue(n.mana==34,"full accessory does not consume energy");h.succeed();}
    @GameTest(template="empty",timeoutTicks=40) public static void harvestPreservesSeparateDrops(GameTestHelper h){var p=AdventureGameTests.player(h);var n=node(h,RouteKind.HARVESTER,new BlockPos(2,2,2),p.getUUID());var result=RouteWork.simulateOutputs(n,java.util.List.of(new ItemStack(Items.WHEAT,2),new ItemStack(Items.WHEAT_SEEDS,3)));h.assertTrue(result!=null&&result[0].is(Items.WHEAT)&&result[1].is(Items.WHEAT_SEEDS),"distinct seeds remain distinct seeds");n.inventory.setItem(4,new ItemStack(Items.WHEAT,64));n.inventory.setItem(5,new ItemStack(Items.WHEAT_SEEDS,64));h.assertTrue(RouteWork.simulateOutputs(n,java.util.List.of(new ItemStack(Items.WHEAT)))==null,"full outputs reject before charging");h.succeed();}
    @GameTest(template="empty",timeoutTicks=40) public static void sourceConvertsDirtOnly(GameTestHelper h){var p=AdventureGameTests.player(h);var at=h.absolutePos(new BlockPos(3,2,3));h.getLevel().setBlock(at,RouteContent.SOIL_SOURCE.get().defaultBlockState(),3);h.getLevel().setBlock(at.east(),Blocks.DIRT.defaultBlockState(),3);h.getLevel().setBlock(at.west(),Blocks.OAK_PLANKS.defaultBlockState(),3);var s=(MagicSoilEntity)h.getLevel().getBlockEntity(at);s.owner=p.getUUID();s.next=0;MagicSoilEntity.tick(h.getLevel(),at,s);h.assertTrue(MagicSoilBlock.isSoil(h.getLevel().getBlockState(at.east())),"dirt becomes magical");h.assertTrue(h.getLevel().getBlockState(at.west()).is(Blocks.OAK_PLANKS),"building survives");h.succeed();}
    @GameTest(template="empty",timeoutTicks=40) public static void infusionChargesExactly100(GameTestHelper h){var p=AdventureGameTests.player(h);var n=node(h,RouteKind.INFUSER,new BlockPos(2,2,2),p.getUUID());n.inventory.setItem(0,new ItemStack(Items.GLASS_BOTTLE,2));n.mana=100;RouteNodeEntity.operate(h.getLevel(),n);h.assertTrue(n.mana==0&&n.inventory.getItem(0).getCount()==1&&PastureBottleLedger.get(h.getLevel()).amount(n.inventory.getItem(4))==100,"one real bottle with exact conserved balance");h.succeed();}
    @GameTest(template="empty",timeoutTicks=80) public static void manaFlowDoesNotUprootPlants(GameTestHelper h){var at=h.absolutePos(new BlockPos(3,2,3));var plant=RouteContent.PLANTS.get(NewPlantKind.COMPOST.id).get();h.getLevel().setBlock(at.below(),Blocks.STONE.defaultBlockState(),3);h.getLevel().setBlock(at.east().below(),RouteContent.SOIL.get().defaultBlockState(),3);h.getLevel().setBlock(at.east(),plant.defaultBlockState(),3);h.assertTrue(h.getLevel().getBlockState(at.east()).canSurvive(h.getLevel(),at.east()),"fixture plant must survive before mana is placed");h.getLevel().setBlock(at,RouteContent.MANA_LIQUID.get().defaultBlockState(),3);h.runAfterDelay(30,()->{h.assertTrue(h.getLevel().getBlockState(at.east()).is(plant),"mana stream must not destroy irrigated magical plant");h.assertTrue(MagicSoilBlock.irrigated(h.getLevel(),at.east().below()),"the surviving plant is actually irrigated");h.succeed();});}
    @GameTest(template="empty",timeoutTicks=40) public static void cageTiersAndCalmWindow(GameTestHelper h){h.assertTrue(PastureCageItem.tierFor("dewbound_whale")==3&&PastureCageItem.tierFor("drumbelly_otter")==2,"special beasts require the right cage");var a=PastureRegistry.TYPES.get("prismatic_antelope").create(h.getLevel());a.calmFor(200);h.assertTrue(a.isCalmed(),"ten-second calm covers eight-second capture");a.discard();h.succeed();}
    @GameTest(template="empty",timeoutTicks=40) public static void catalogueUsesRegisteredOwnItems(GameTestHelper h){try(var stream=RouteGameTests.class.getResourceAsStream("/data/tnc/life_routes/catalogue.json")){var root=com.google.gson.JsonParser.parseReader(new java.io.InputStreamReader(stream,java.nio.charset.StandardCharsets.UTF_8)).getAsJsonObject();h.assertTrue(root.getAsJsonArray("magic").size()==38&&root.getAsJsonArray("animals").size()==26,"complete species catalogue");for(var list:java.util.List.of("magic","animals","machines"))for(var entry:root.getAsJsonArray(list)){var e=entry.getAsJsonObject();for(var key:java.util.List.of("seed","product","id")){if(!e.has(key)||list.equals("animals")&&key.equals("id"))continue;String name=e.get(key).getAsString();if(name.equals("stored_mana")||list.equals("magic")&&key.equals("id"))continue;var item=RouteContent.item(name);h.assertTrue(item!=null&&item!=Items.AIR,"catalogue missing registered item: "+name);}}h.succeed();}catch(java.io.IOException e){throw new RuntimeException(e);}}
    @GameTest(template="empty",timeoutTicks=40) public static void sharedWireBudgetAndMirrorsConserve(GameTestHelper h){var owner=AdventureGameTests.player(h).getUUID();var a=node(h,RouteKind.MIRROR,new BlockPos(1,2,1),owner);var b=node(h,RouteKind.MIRROR,new BlockPos(2,2,1),owner);var sink=node(h,RouteKind.SAWMILL,new BlockPos(3,2,1),owner);a.mana=196;b.mana=200;RouteNetwork.add(h.getLevel(),a.getBlockPos());RouteNetwork.add(h.getLevel(),b.getBlockPos());RouteNetwork.add(h.getLevel(),sink.getBlockPos());RouteNetwork.tickNetwork(h.getLevel());h.assertTrue(sink.mana>0,"consumer receives despite nearly-full adjacent relay buffers");h.assertTrue(a.mana+b.mana+sink.mana==396,"relay transfer conserves mana");h.assertTrue(sink.mana<=4,"shared mirror path has one four-per-second budget");h.succeed();}
    @GameTest(template="empty",timeoutTicks=40) public static void bucketCannotReplaceCultivatedPlant(GameTestHelper h){var p=AdventureGameTests.player(h);var at=h.absolutePos(new BlockPos(2,2,2));var crop=RouteContent.PLANTS.get("dream_compost").get();h.getLevel().setBlock(at.below(),RouteContent.SOIL.get().defaultBlockState(),3);h.getLevel().setBlock(at,crop.defaultBlockState(),3);boolean placed=((ManaBucketItem)RouteContent.MANA_BUCKET.get()).emptyContents(p,h.getLevel(),at,null);h.assertTrue(!placed&&h.getLevel().getBlockState(at).is(crop),"direct bucket placement preserves crops too");h.succeed();}
    @GameTest(template="empty",timeoutTicks=40) public static void animalChargeAndDrawShareRealBalance(GameTestHelper h){var p=AdventureGameTests.player(h);var a=PastureRegistry.TYPES.get("dewbound_whale").create(h.getLevel());a.moveTo(h.absolutePos(new BlockPos(2,2,2)),0,0);var data=new net.minecraft.nbt.CompoundTag();a.saveWithoutId(data);data.putUUID("PastureOwner",p.getUUID());a.readAdditionalSaveData(data);h.assertTrue(a.receiveNetworkMana(p.getUUID(),100)==32,"whale receives at most 32 each second");h.assertTrue(a.receiveNetworkMana(p.getUUID(),100)==0,"multiple ports cannot duplicate receiving bandwidth");h.assertTrue(a.drawNetworkMana(p.getUUID(),100,false)==32&&a.storedResource()==0,"same received balance can be recovered once");h.assertTrue(a.drawNetworkMana(p.getUUID(),100,false)==0,"no duplicate discharge");a.discard();h.succeed();}
    @GameTest(template="empty",timeoutTicks=40) public static void craftingFourIndependentBottlesProducesBucket(GameTestHelper h){var p=AdventureGameTests.player(h);var menu=new CraftingMenu(1,p.getInventory(),ContainerLevelAccess.create(h.getLevel(),h.absolutePos(new BlockPos(2,1,2))));p.containerMenu=menu;var bottles=new java.util.ArrayList<ItemStack>();for(int i=1;i<=4;i++){var b=full(h);bottles.add(b);menu.getSlot(i).set(b);}menu.getSlot(5).set(new ItemStack(Items.BUCKET));menu.slotsChanged(menu.getSlot(1).container);h.assertTrue(menu.getSlot(0).getItem().is(RouteContent.MANA_BUCKET.get()),"four independent balances make fluid bucket");menu.clicked(0,0,ClickType.PICKUP,p);h.assertTrue(menu.getCarried().is(RouteContent.MANA_BUCKET.get()),"actual crafted bucket");h.assertTrue(bottles.stream().allMatch(b->PastureBottleLedger.get(h.getLevel()).amount(b)==0),"all four balances debited exactly once");h.succeed();}
}
