package com.tnc.tnc.life.routes;
import java.util.*;
import net.minecraft.core.*;
import net.minecraft.server.level.*;
import net.minecraft.world.entity.*;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.*;
import net.minecraftforge.event.level.*;
import net.minecraftforge.event.entity.living.*;
import net.minecraftforge.event.entity.player.*;
import net.minecraftforge.eventbus.api.*;
import net.minecraftforge.fml.common.Mod;
@Mod.EventBusSubscriber(modid="tnc")
public final class RouteEvents {
    @SubscribeEvent public static void placed(BlockEvent.EntityPlaceEvent e){if(e.getEntity() instanceof ServerPlayer p&&!e.isCanceled()){var id=net.minecraftforge.registries.ForgeRegistries.BLOCKS.getKey(e.getPlacedBlock().getBlock());if(id!=null){RouteProgress.award(p,"plant/"+id.getPath());if(e.getPlacedBlock().getBlock() instanceof CropBlock)RouteProgress.award(p,"traditional/planted");if(id.getPath().endsWith("_ore"))RouteOreLedger.get(p.serverLevel()).placed(e.getPos());}}}
    @SubscribeEvent(priority=EventPriority.LOWEST) public static void breaking(BlockEvent.BreakEvent e){if(e.isCanceled()||!(e.getPlayer() instanceof ServerPlayer p))return;var state=e.getState();if(RoutePlanting.magic(state)){boolean mature=false;for(var property:state.getProperties())if(property.getName().equals("age")&&state.getValue(property) instanceof Integer age)mature=age==property.getPossibleValues().stream().filter(Integer.class::isInstance).mapToInt(v->(Integer)v).max().orElse(-1);if(state.hasProperty(com.tnc.tnc.life.HomewardFlower.FlowerBlock.BLOOMING))mature=state.getValue(com.tnc.tnc.life.HomewardFlower.FlowerBlock.BLOOMING);if(mature){var id=net.minecraftforge.registries.ForgeRegistries.BLOCKS.getKey(state.getBlock());RouteProgress.award(p,"harvest/"+id.getPath());}}if(state.getBlock() instanceof CropBlock crop&&crop.isMaxAge(state)){RouteProgress.award(p,"traditional/harvested");var id=net.minecraftforge.registries.ForgeRegistries.BLOCKS.getKey(state.getBlock());if(id!=null)RouteProgress.award(p,"harvest/"+id.getPath());}}
    @SubscribeEvent public static void ward(LivingHurtEvent e){if(!(e.getEntity() instanceof ServerPlayer p)||e.getAmount()<=0)return;var item=p.getOffhandItem();if(item.getItem() instanceof RouteAccessory a&&a.kind==RouteAccessory.Kind.WARD&&p.level().getGameTime()>=p.getPersistentData().getLong("DewWardUntil")){float absorb=Math.min(2,e.getAmount());int cost=(int)Math.ceil(absorb*12);if(RouteChargeLedger.get(p.serverLevel()).spend(item,cost)){e.setAmount(e.getAmount()-absorb);p.getPersistentData().putLong("DewWardUntil",p.level().getGameTime()+40);}}}
    @SubscribeEvent(priority=EventPriority.HIGH) public static void bind(PlayerInteractEvent.RightClickBlock e){if(!(e.getEntity() instanceof ServerPlayer p)||!(e.getItemStack().getItem() instanceof com.tnc.tnc.life.pasture.PastureStaffItem)||!e.getItemStack().hasTag())return;var tag=e.getItemStack().getTag();if(tag.hasUUID("Animal")&&p.serverLevel().getBlockEntity(e.getPos()) instanceof RouteNodeEntity node&&(node.kind()==RouteKind.ANIMAL_COLLECTOR||node.kind()==RouteKind.COLOR_TARGET)&&node.mayUse(p)){var beast=p.serverLevel().getEntity(tag.getUUID("Animal"));if(beast instanceof com.tnc.tnc.life.pasture.PastureAnimal animal&&p.getUUID().equals(animal.owner())){node.animal=animal.getUUID();animal.getPersistentData().putBoolean("ManaWorkEnabled",true);node.setChanged();p.displayClientMessage(net.minecraft.network.chat.Component.literal("已绑定 "+animal.species().name()),true);e.setCancellationResult(net.minecraft.world.InteractionResult.SUCCESS);e.setCanceled(true);}}}
    @SubscribeEvent public static void lightning(net.minecraftforge.event.entity.EntityStruckByLightningEvent e){if(e.getLightning().getCause()!=null||e.getLightning().getPersistentData().getBoolean("TncArtificial"))return;if(e.getEntity() instanceof com.tnc.tnc.life.pasture.PastureAnimal a&&a.speciesId().equals("wirecall_lizard")){var data=a.getPersistentData();if(!data.hasUUID("NaturalBolt")||!data.getUUID("NaturalBolt").equals(e.getLightning().getUUID())){data.putUUID("NaturalBolt",e.getLightning().getUUID());a.receiveStaticCharge(Math.min(1200,2400-a.storedResource()));}e.setCanceled(true);}}
    @SubscribeEvent public static void stop(net.minecraftforge.event.server.ServerStoppedEvent e){com.tnc.tnc.life.pasture.PastureCageItem.clearSessions();}
    @SubscribeEvent public static void chapterCraft(PlayerEvent.ItemCraftedEvent e){if(e.getEntity() instanceof ServerPlayer p&&e.getCrafting().isEdible())RouteProgress.award(p,"traditional/cooked");}
    @SubscribeEvent(priority=EventPriority.LOWEST) public static void animalDrops(LivingDropsEvent e){if(e.isCanceled()||!(e.getSource().getEntity() instanceof ServerPlayer p)||!(e.getEntity() instanceof com.tnc.tnc.life.pasture.PastureAnimal a)||a.isBaby()||e.getDrops().isEmpty())return;RouteProgress.award(p,"harvest/"+a.speciesId());}
}
