StartupEvents.registry('item', event => {
  const SCROLL_TEXTURES = {
    arcane: 'kubejs:item/scroll_arcane',
    fire: 'kubejs:item/scroll_fire',
    frost: 'kubejs:item/scroll_frost',
    physical_melee: 'kubejs:item/scroll',
    healing: 'kubejs:item/scroll_holy',
    water: 'kubejs:item/scroll_water',
    earth: 'kubejs:item/scroll_earth',
    air: 'kubejs:item/scroll_wind',
    lightning: 'kubejs:item/scroll_lightning',
    physical_ranged: 'kubejs:item/scroll_ranger'
  };

  const SCROLL_ITEM_ID_OVERRIDES = {
    'rogues:whirlwind': 'whirlwind1_scroll',
    'ysjxspells:terra_earthquake': 'ysjxspells_terra_earthquake_scroll'
  };

  const EPIC_SPELL_IDS = [
    'ysjxspells:fengshenzhishi',
    'ysjxspells:tianxing',
    'ysjxspells:lingyuleiji',
    'ysjxspells:heidong',
    'ysjxspells:huoyun_gaojie',
    'ysjxspells:mikaerzhufu_gao',
    'ysjxspells:bingdongfazhen',
    'ysjxspells:haiyangjiejie',
    'ysjxspells:malkuth_giant_sword_slash',
    'ysjxspells:jianyu_gaojie'
  ];

  const EPIC_SPELL_PREFIXES = [
    'ysjxspells:atomic_',
    'ysjxspells:xushici_',
    'ysjxspells:explosion_'
  ];

  function isEpicSpell(spellId) {
    if (EPIC_SPELL_IDS.indexOf(spellId) !== -1) {
      return true;
    }

    for (let i = 0; i < EPIC_SPELL_PREFIXES.length; i++) {
      if (spellId.indexOf(EPIC_SPELL_PREFIXES[i]) === 0) {
        return true;
      }
    }

    return false;
  }

  const SPELLS_BY_SCHOOL = {
    arcane: [
      { spell: 'lne_wizards:arcane_starfall', name: '星陨' },
      { spell: 'spellbladenext:amethystslash', name: '紫晶飞溅' },
      { spell: 'spellbladenext:arcaneflourish', name: '奥术回旋' },
      { spell: 'spellbladenext:bladestorm', name: '回响风暴' },
      { spell: 'spellbladenext:eldritchblast', name: '回响射线' },
      { spell: 'spellbladenext:finalstrike', name: '音速斩' },
      { spell: 'spellbladenext:frostblink', name: '奥术闪现' },
      { spell: 'spellbladenext:maelstrom', name: '大漩涡' },
      { spell: 'spellbladenext:starfall', name: '星辰坠落' },
      { spell: 'wizards:arcane_beam', name: '奥术射线' },
      { spell: 'wizards:arcane_blast', name: '奥术冲击' },
      { spell: 'wizards:arcane_blink', name: '闪现' },
      { spell: 'wizards:arcane_bolt', name: '奥术弹' },
      { spell: 'wizards:arcane_missile', name: '奥术飞弹' },
      { spell: 'ysjxspells:abyss_blast_portal_arcane', name: '深渊水涌（奥术）' },
      { spell: 'ysjxspells:aoshufeidan_upgraded', name: '奥术飞弹（升级）' },
      { spell: 'ysjxspells:aoshuqianghua', name: '奥术强化' },
      { spell: 'ysjxspells:atomic_arcane', name: 'Atomic（奥术）' },
      { spell: 'ysjxspells:bingci1_arcane', name: '冰刺（初阶·奥术）' },
      { spell: 'ysjxspells:bingci2_arcane', name: '冰刺（升级·奥术）' },
      { spell: 'ysjxspells:cibeishexian_arcane', name: '慈悲射线（初阶·奥术）' },
      { spell: 'ysjxspells:cibeishexian2_arcane', name: '慈悲射线（升级·奥术）' },
      { spell: 'ysjxspells:cj_flame_strike_arcane', name: '烈焰打击（初阶·奥术）' },
      { spell: 'ysjxspells:cj_huanyingji_arcane', name: '幻影戟（初阶·奥术）' },
      { spell: 'ysjxspells:cj_luohunren_arcane', name: '落魂刃（初阶·奥术）' },
      { spell: 'ysjxspells:cj_water_wave_arcane', name: '海浪打击（初阶·奥术）' },
      { spell: 'ysjxspells:divine_gear_arcane', name: '神圣齿轮（奥术）' },
      { spell: 'ysjxspells:explosion_arcane', name: '爆裂魔法（奥术）' },
      { spell: 'ysjxspells:flame_strike_arcane', name: '烈焰打击（升级·奥术）' },
      { spell: 'ysjxspells:heidong', name: '黑洞' },
      { spell: 'ysjxspells:huanmo1_arcane', name: '唤魔尖牙（初阶·奥术）' },
      { spell: 'ysjxspells:huanmo2_arcane', name: '唤魔尖牙（中阶·奥术）' },
      { spell: 'ysjxspells:huanyingji_arcane', name: '幻影戟（奥术）' },
      { spell: 'ysjxspells:jianjizhedaodan_arcane', name: '歼击者导弹（奥术）' },
      { spell: 'ysjxspells:luohunren_arcane', name: '落魂刃（升级·奥术）' },
      { spell: 'ysjxspells:lvyanqiangxi', name: '绿焰强袭（奥术）' },
      { spell: 'ysjxspells:sandstorm_arcane', name: '沙暴缠绕（奥术）' },
      { spell: 'ysjxspells:scrap_drone_arcane', name: '破片无人机（奥术）' },
      { spell: 'ysjxspells:scrap_drone_basic_arcane', name: '破片无人机（初阶·奥术）' },
      { spell: 'ysjxspells:soul_flame_strike_arcane', name: '魂焰打击（奥术）' },
      { spell: 'ysjxspells:turret_arcane', name: '圣城炮塔（奥术）' },
      { spell: 'ysjxspells:turret_basic_arcane', name: '圣城炮塔（初阶·奥术）' },
      { spell: 'ysjxspells:water_wave_arcane', name: '海浪打击（奥术）' },
      { spell: 'ysjxspells:xiajiepaodan_arcane', name: '下界炮弹（奥术）' },
      { spell: 'ysjxspells:xianqudaodan_arcane', name: '先驱导弹（奥术）' },
      { spell: 'ysjxspells:xukongfuwen_arcane', name: '虚空符文（奥术）' },
      { spell: 'ysjxspells:xushici_arcane', name: '虚式茈（奥术）' },
      { spell: 'ysjxspells:yanmiechuansongmen_arcane', name: '湮灭传送门（奥术）' },
      { spell: 'ysjxspells:yanmiezhadan', name: '湮灭炸弹（奥术）' }
    ],

    fire: [
      { spell: 'lne_wizards:fire_flamerush', name: '烈焰疾驰' },
      { spell: 'spellbladenext:combustion', name: '凤凰诅咒' },
      { spell: 'spellbladenext:fireflourish', name: '火焰回旋' },
      { spell: 'spellbladenext:flamelance', name: '火焰长枪' },
      { spell: 'spellbladenext:flameslash', name: '炽焰割裂' },
      { spell: 'spellbladenext:flicker_strike', name: '闪烁之炎' },
      { spell: 'spellbladenext:frostvert', name: '龙焰猛击' },
      { spell: 'spellbladenext:inferno', name: '炼狱' },
      { spell: 'spellbladenext:phoenixdive', name: '凤凰俯冲' },
      { spell: 'spellbladenext:snuffout', name: '野火' },
      { spell: 'wizards:fire_breath', name: '烈焰吐息' },
      { spell: 'wizards:fire_meteor', name: '陨石术' },
      { spell: 'wizards:fire_scorch', name: '灼烧术' },
      { spell: 'wizards:fire_wall', name: '烈焰之墙' },
      { spell: 'wizards:fireball', name: '火球术' },
      { spell: 'ysjxspells:abyss_blast_portal_fire', name: '深渊水涌（火焰）' },
      { spell: 'ysjxspells:atomic_fire', name: 'Atomic（火焰）' },
      { spell: 'ysjxspells:bingci1_fire', name: '冰刺（初阶·火焰）' },
      { spell: 'ysjxspells:bingci2_fire', name: '冰刺（升级·火焰）' },
      { spell: 'ysjxspells:cibeishexian_fire', name: '慈悲射线（初阶·火焰）' },
      { spell: 'ysjxspells:cibeishexian2_fire', name: '慈悲射线（升级·火焰）' },
      { spell: 'ysjxspells:cj_flame_strike_fire', name: '烈焰打击（初阶·火焰）' },
      { spell: 'ysjxspells:cj_huanyingji_fire', name: '幻影戟（初阶·火焰）' },
      { spell: 'ysjxspells:cj_luohunren_fire', name: '落魂刃（初阶·火焰）' },
      { spell: 'ysjxspells:cj_water_wave_fire', name: '海浪打击（初阶·火焰）' },
      { spell: 'ysjxspells:divine_gear_fire', name: '神圣齿轮（火焰）' },
      { spell: 'ysjxspells:explosion_fire', name: '爆裂魔法（火焰）' },
      { spell: 'ysjxspells:flame_strike_fire', name: '烈焰打击（升级·火焰）' },
      { spell: 'ysjxspells:huanmo1_fire', name: '唤魔尖牙（初阶·火焰）' },
      { spell: 'ysjxspells:huanmo2_fire', name: '唤魔尖牙（中阶·火焰）' },
      { spell: 'ysjxspells:huanyingji_fire', name: '幻影戟（火焰）' },
      { spell: 'ysjxspells:huoyanfeidan_upgraded', name: '火球术（升级）' },
      { spell: 'ysjxspells:huoyanqianghua', name: '火焰强化' },
      { spell: 'ysjxspells:huoyun_gaojie', name: '火陨（高阶）' },
      { spell: 'ysjxspells:jianjizhedaodan_fire', name: '歼击者导弹（火焰）' },
      { spell: 'ysjxspells:luohunren_fire', name: '落魂刃（升级·火焰）' },
      { spell: 'ysjxspells:lvyanqiangxi_fire', name: '绿焰强袭（火焰）' },
      { spell: 'ysjxspells:malkuth_fireball_fire', name: '玛尔库特火球' },
      { spell: 'ysjxspells:sandstorm_fire', name: '沙暴缠绕（火焰）' },
      { spell: 'ysjxspells:scrap_drone_basic_fire', name: '破片无人机（初阶·火焰）' },
      { spell: 'ysjxspells:scrap_drone_fire', name: '破片无人机（火焰）' },
      { spell: 'ysjxspells:soul_flame_strike_fire', name: '魂焰打击（火焰）' },
      { spell: 'ysjxspells:turret_basic_fire', name: '圣城炮塔（初阶·火焰）' },
      { spell: 'ysjxspells:turret_fire', name: '圣城炮塔（火焰）' },
      { spell: 'ysjxspells:wangguohuopao', name: '王国火炮' },
      { spell: 'ysjxspells:water_wave_fire', name: '海浪打击（火焰）' },
      { spell: 'ysjxspells:xiajiepaodan_fire', name: '下界炮弹（火焰）' },
      { spell: 'ysjxspells:xianqudaodan_fire', name: '先驱导弹（火焰）' },
      { spell: 'ysjxspells:xukongfuwen_fire', name: '虚空符文（火焰）' },
      { spell: 'ysjxspells:xushici_fire', name: '虚式茈（火焰）' },
      { spell: 'ysjxspells:yanmiechuansongmen_fire', name: '湮灭传送门（火焰）' },
      { spell: 'ysjxspells:yanmiezhadan_fire', name: '湮灭炸弹（火焰）' }
    ],

    frost: [
      { spell: 'lne_wizards:frost_ray', name: '冰霜射线' },
      { spell: 'spellbladenext:coldbuff', name: '极寒侵袭' },
      { spell: 'spellbladenext:deathchill', name: '死亡寒印' },
      { spell: 'spellbladenext:eviscerate', name: '屠戮' },
      { spell: 'spellbladenext:frostbloom0', name: '冰花涌流' },
      { spell: 'spellbladenext:frostflourish', name: '冰霜回旋' },
      { spell: 'spellbladenext:frostgrasp', name: '寒冬之握' },
      { spell: 'spellbladenext:frostslash', name: '刀刃乱舞' },
      { spell: 'spellbladenext:tempest', name: '暴风雪' },
      { spell: 'spellbladenext:whirlingblades', name: '激流' },
      { spell: 'wizards:frost_blizzard', name: '暴风雪' },
      { spell: 'wizards:frost_nova', name: '冰霜新星' },
      { spell: 'wizards:frost_shard', name: '冰霜碎片' },
      { spell: 'wizards:frost_shield', name: '冰霜护盾' },
      { spell: 'wizards:frostbolt', name: '冰霜箭' },
      { spell: 'ysjxspells:abyss_blast_portal_frost', name: '深渊水涌（冰霜）' },
      { spell: 'ysjxspells:atomic_frost', name: 'Atomic（冰霜）' },
      { spell: 'ysjxspells:bingci1_frost', name: '冰刺（初阶·冰霜）' },
      { spell: 'ysjxspells:bingci2_frost', name: '冰刺（升级·冰霜）' },
      { spell: 'ysjxspells:bingdongfazhen', name: '冰霜领域' },
      { spell: 'ysjxspells:bingshuangfeidan_upgraded', name: '冰霜飞弹（升级）' },
      { spell: 'ysjxspells:bingshuangqianghua', name: '冰霜强化' },
      { spell: 'ysjxspells:cibeishexian_frost', name: '慈悲射线（初阶·冰霜）' },
      { spell: 'ysjxspells:cibeishexian2_frost', name: '慈悲射线（升级·冰霜）' },
      { spell: 'ysjxspells:cj_flame_strike_frost', name: '烈焰打击（初阶·冰霜）' },
      { spell: 'ysjxspells:cj_huanyingji_frost', name: '幻影戟（初阶·冰霜）' },
      { spell: 'ysjxspells:cj_luohunren_frost', name: '落魂刃（初阶·冰霜）' },
      { spell: 'ysjxspells:cj_water_wave_frost', name: '海浪打击（初阶·冰霜）' },
      { spell: 'ysjxspells:divine_gear_frost', name: '神圣齿轮（冰霜）' },
      { spell: 'ysjxspells:explosion_frost', name: '爆裂魔法（冰霜）' },
      { spell: 'ysjxspells:flame_strike_frost', name: '烈焰打击（升级·冰霜）' },
      { spell: 'ysjxspells:frostnova_lullabye', name: '霜星摇篮曲' },
      { spell: 'ysjxspells:huanmo1_frost', name: '唤魔尖牙（初阶·冰霜）' },
      { spell: 'ysjxspells:huanmo2_frost', name: '唤魔尖牙（中阶·冰霜）' },
      { spell: 'ysjxspells:huanyingji_frost', name: '幻影戟（冰霜）' },
      { spell: 'ysjxspells:jianjizhedaodan_frost', name: '歼击者导弹（冰霜）' },
      { spell: 'ysjxspells:luohunren_frost', name: '落魂刃（升级·冰霜）' },
      { spell: 'ysjxspells:lvyanqiangxi_frost', name: '绿焰强袭（冰霜）' },
      { spell: 'ysjxspells:malkuth_fireball_ice', name: '玛尔库特冰球' },
      { spell: 'ysjxspells:sandstorm_frost', name: '沙暴缠绕（冰霜）' },
      { spell: 'ysjxspells:scrap_drone_basic_frost', name: '破片无人机（初阶·冰霜）' },
      { spell: 'ysjxspells:scrap_drone_frost', name: '破片无人机（冰霜）' },
      { spell: 'ysjxspells:soul_flame_strike_frost', name: '魂焰打击（冰霜）' },
      { spell: 'ysjxspells:turret_basic_frost', name: '圣城炮塔（初阶·冰霜）' },
      { spell: 'ysjxspells:turret_frost', name: '圣城炮塔（冰霜）' },
      { spell: 'ysjxspells:wangguobingpao', name: '王国冰炮' },
      { spell: 'ysjxspells:water_wave_frost', name: '海浪打击（冰霜）' },
      { spell: 'ysjxspells:xiajiepaodan_frost', name: '下界炮弹（冰霜）' },
      { spell: 'ysjxspells:xianqudaodan_frost', name: '先驱导弹（冰霜）' },
      { spell: 'ysjxspells:xukongfuwen_frost', name: '虚空符文（冰霜）' },
      { spell: 'ysjxspells:xushici_frost', name: '虚式茈（冰霜）' },
      { spell: 'ysjxspells:yanmiechuansongmen_frost', name: '湮灭传送门（冰霜）' },
      { spell: 'ysjxspells:yanmiezhadan_frost', name: '湮灭炸弹（冰霜）' }
    ],

    physical_melee: [
      { spell: 'lne_rogues:dancing_dagger', name: '飞舞匕首' },
      { spell: 'lne_rogues:second_wind', name: '复苏之风' },
      { spell: 'rogues:charge', name: '冲锋' },
      { spell: 'rogues:shadow_step', name: '暗影步' },
      { spell: 'rogues:shock_powder', name: '震击粉末' },
      { spell: 'rogues:shout', name: '挫志怒吼' },
      { spell: 'rogues:slice_and_dice', name: '切割' },
      { spell: 'rogues:throw', name: '碎裂投掷' },
      { spell: 'rogues:vanish', name: '消失' },
      { spell: 'rogues:whirlwind', name: '旋风斩' },
      { spell: 'spellbladenext:monkeyreflect', name: '撕裂之风' },
      { spell: 'spellbladenext:monkeyslam', name: '腾跃猛击' },
      { spell: 'spellbladenext:reckoning', name: '猴王裁决' },
      { spell: 'spellbladenext:staffstrike', name: '棍棒猛击' },
      { spell: 'spellbladenext:whirlwind', name: '旋风斩' },
      { spell: 'spellbladenext:defiance_of_destiny', name: '不屈姿态' },
      { spell: 'spellbladenext:shield_shatter', name: '盾牌碎裂' },
      { spell: 'berserker_rpg:blood_reckoning', name: '血之清算' },
      { spell: 'berserker_rpg:bloody_strike', name: '血腥打击' },
      { spell: 'berserker_rpg:nordic_storm', name: '北境风暴' },
      { spell: 'berserker_rpg:outrage', name: '暴怒' },
      { spell: 'berserker_rpg:rumbling_swing', name: '雷鸣挥击' },
      { spell: 'berserker_rpg:thunder_call', name: '托兰之唤' },
      { spell: 'berserker_rpg:undertow', name: '暗流' },
      { spell: 'berserker_rpg:wild_rage', name: '野性狂怒' },
      { spell: 'paladins:judgement', name: '审判' },
      { spell: 'ysjxspells:abyss_blast_portal_wuli', name: '深渊水涌（物理）' },
      { spell: 'ysjxspells:aolafu_q', name: '逆流投掷' },
      { spell: 'ysjxspells:atomic_wuli', name: 'Atomic（物理）' },
      { spell: 'ysjxspells:bingci1_wuli', name: '冰刺（初阶·物理）' },
      { spell: 'ysjxspells:bingci2_wuli', name: '冰刺（升级·物理）' },
      { spell: 'ysjxspells:cibeishexian_wuli', name: '慈悲射线（初阶·物理）' },
      { spell: 'ysjxspells:cibeishexian2_wuli', name: '慈悲射线（升级·物理）' },
      { spell: 'ysjxspells:cj_flame_strike_wuli', name: '烈焰打击（初阶·物理）' },
      { spell: 'ysjxspells:cj_huanyingji_wuli', name: '幻影戟（初阶·物理）' },
      { spell: 'ysjxspells:cj_luohunren_wuli', name: '落魂刃（初阶·物理）' },
      { spell: 'ysjxspells:cj_water_wave_wuli', name: '海浪打击（初阶·物理）' },
      { spell: 'ysjxspells:cleave', name: '顺劈' },
      { spell: 'ysjxspells:divine_gear_wuli', name: '神圣齿轮（物理）' },
      { spell: 'ysjxspells:explosion_wuli', name: '爆裂魔法（物理）' },
      { spell: 'ysjxspells:fan_of_knives', name: '飞刀扇' },
      { spell: 'ysjxspells:fengbaojushe', name: '风暴巨蛇' },
      { spell: 'ysjxspells:flame_strike_wuli', name: '烈焰打击（升级·物理）' },
      { spell: 'ysjxspells:huanmo1_wuli', name: '唤魔尖牙（初阶·物理）' },
      { spell: 'ysjxspells:huanmo2_wuli', name: '唤魔尖牙（中阶·物理）' },
      { spell: 'ysjxspells:huanyingji_shanxing_wuli', name: '扇形幻影戟' },
      { spell: 'ysjxspells:huanyingji_wuli', name: '幻影戟（物理）' },
      { spell: 'ysjxspells:jianjizhedaodan_wuli', name: '歼击者导弹（物理）' },
      { spell: 'ysjxspells:lvyanqiangxi_wuli', name: '绿焰强袭（物理）' },
      { spell: 'ysjxspells:malkuth_giant_sword_slash', name: '冰焰巨剑斩' },
      { spell: 'ysjxspells:sandstorm_wuli', name: '沙暴缠绕（物理）' },
      { spell: 'ysjxspells:scrap_drone_basic_wuli', name: '破片无人机（初阶·物理）' },
      { spell: 'ysjxspells:scrap_drone_wuli', name: '破片无人机（物理）' },
      { spell: 'ysjxspells:shejiqianghua', name: '射击强化' },
      { spell: 'ysjxspells:soul_flame_strike_wuli', name: '魂焰打击（物理）' },
      { spell: 'ysjxspells:swift_strikes', name: '迅捷连斩' },
      { spell: 'ysjxspells:tiaozhan', name: '灵跃斩' },
      { spell: 'ysjxspells:turret_basic_wuli', name: '圣城炮塔（初阶·物理）' },
      { spell: 'ysjxspells:turret_wuli', name: '圣城炮塔（物理）' },
      { spell: 'ysjxspells:wanglingdun', name: '亡灵盾' },
      { spell: 'ysjxspells:water_wave_wuli', name: '海浪打击（物理）' },
      { spell: 'ysjxspells:wuliqianghua', name: '物理强化' },
      { spell: 'ysjxspells:wulislash', name: '物理斩击（初阶）' },
      { spell: 'ysjxspells:wulislash_2', name: '物理斩击（中阶）' },
      { spell: 'ysjxspells:wulislash_3', name: '物理斩击（高阶）' },
      { spell: 'ysjxspells:xiajiepaodan_wuli', name: '下界炮弹（物理）' },
      { spell: 'ysjxspells:xianqudaodan_wuli', name: '先驱导弹（物理）' },
      { spell: 'ysjxspells:xukongfuwen_wuli', name: '虚空符文（物理）' },
      { spell: 'ysjxspells:xushici_wuli', name: '虚式茈（物理）' },
      { spell: 'ysjxspells:yanmiechuansongmen_wuli', name: '湮灭传送门（物理）' },
      { spell: 'ysjxspells:yanmiezhadan_wuli', name: '湮灭炸弹（物理）' },
      { spell: 'ysjxspells:zhanfutouzhi', name: '战斧投掷' },
      { spell: 'ysjxspells:zhongyashalou', name: '中娅沙漏' }
    ],

    healing: [
      { spell: 'lne_paladins:holy_prevention', name: '圣佑结界' },
      { spell: 'lne_paladins:holy_weapon', name: '神圣武器' },
      { spell: 'paladins:barrier', name: '屏障' },
      { spell: 'paladins:battle_banner', name: '战旗' },
      { spell: 'paladins:circle_of_healing', name: '治疗之环' },
      { spell: 'paladins:divine_protection', name: '神圣庇护' },
      { spell: 'paladins:flash_heal', name: '快速治疗' },
      { spell: 'paladins:heal', name: '治疗术' },
      { spell: 'paladins:holy_beam', name: '圣光术' },
      { spell: 'paladins:holy_shock', name: '神圣震击' },
      { spell: 'spellbladenext:bolster', name: '护甲强化' },
      { spell: 'spellbladenext:challenge', name: '激怒' },
      { spell: 'spellbladenext:inexorable', name: '势不可挡' },
      { spell: 'spellbladenext:overpower', name: '压制' },
      { spell: 'spellbladenext:smite', name: '神圣惩击' },
      { spell: 'spellbladenext:soul_of_vengeance', name: '复仇之魂' },
      { spell: 'ysjxspells:abyss_blast_portal_healing', name: '深渊水涌（神圣）' },
      { spell: 'ysjxspells:atomic_healing', name: 'Atomic（神圣）' },
      { spell: 'ysjxspells:bingci1_healing', name: '冰刺（初阶·神圣）' },
      { spell: 'ysjxspells:bingci2_healing', name: '冰刺（升级·神圣）' },
      { spell: 'ysjxspells:cibeishexian_healing', name: '慈悲射线（初阶·神圣）' },
      { spell: 'ysjxspells:cibeishexian2_healing', name: '慈悲射线（升级·神圣）' },
      { spell: 'ysjxspells:cj_flame_strike_healing', name: '烈焰打击（初阶·神圣）' },
      { spell: 'ysjxspells:cj_huanyingji_healing', name: '幻影戟（初阶·神圣）' },
      { spell: 'ysjxspells:cj_luohunren_healing', name: '落魂刃（初阶·神圣）' },
      { spell: 'ysjxspells:cj_water_wave_healing', name: '海浪打击（初阶·神圣）' },
      { spell: 'ysjxspells:divine_gear_healing', name: '神圣齿轮（神圣）' },
      { spell: 'ysjxspells:explosion_healing', name: '爆裂魔法（神圣）' },
      { spell: 'ysjxspells:flame_strike_healing', name: '烈焰打击（升级·神圣）' },
      { spell: 'ysjxspells:huanmo1_healing', name: '唤魔尖牙（初阶·神圣）' },
      { spell: 'ysjxspells:huanmo2_healing', name: '唤魔尖牙（中阶·神圣）' },
      { spell: 'ysjxspells:huanyingji_healing', name: '幻影戟（神圣）' },
      { spell: 'ysjxspells:jianjizhedaodan_healing', name: '歼击者导弹（神圣）' },
      { spell: 'ysjxspells:luohunren_healing', name: '落魂刃（升级·神圣）' },
      { spell: 'ysjxspells:lvyanqiangxi_healing', name: '绿焰强袭（神圣）' },
      { spell: 'ysjxspells:mikaerzhufu', name: '米凯尔祝福' },
      { spell: 'ysjxspells:mikaerzhufu_gao', name: '天使的赐福' },
      { spell: 'ysjxspells:sandstorm_healing', name: '沙暴缠绕（神圣）' },
      { spell: 'ysjxspells:scrap_drone_basic_healing', name: '破片无人机（初阶·神圣）' },
      { spell: 'ysjxspells:scrap_drone_healing', name: '破片无人机（神圣）' },
      { spell: 'ysjxspells:shenshengqianghua', name: '神圣强化' },
      { spell: 'ysjxspells:soul_flame_strike_healing', name: '魂焰打击（神圣）' },
      { spell: 'ysjxspells:turret_basic_healing', name: '圣城炮塔（初阶·神圣）' },
      { spell: 'ysjxspells:turret_healing', name: '圣城炮塔（神圣）' },
      { spell: 'ysjxspells:water_wave_healing', name: '海浪打击（神圣）' },
      { spell: 'ysjxspells:xiajiepaodan_healing', name: '下界炮弹（神圣）' },
      { spell: 'ysjxspells:xianqudaodan_healing', name: '先驱导弹（神圣）' },
      { spell: 'ysjxspells:xukongfuwen_healing', name: '虚空符文（神圣）' },
      { spell: 'ysjxspells:xushici_healing', name: '虚式茈（神圣）' },
      { spell: 'ysjxspells:yanmiechuansongmen_healing', name: '湮灭传送门（神圣）' },
      { spell: 'ysjxspells:yanmiezhadan_healing', name: '湮灭炸弹（神圣）' }
    ],

    water: [
      { spell: 'elemental_wizards_rpg:aqua_bubble_beam', name: '泡泡射线' },
      { spell: 'elemental_wizards_rpg:aqua_explosive_bubbles', name: '爆裂泡泡' },
      { spell: 'elemental_wizards_rpg:aqua_hydro_beam', name: '高压水流' },
      { spell: 'elemental_wizards_rpg:aqua_splash', name: '水花飞溅' },
      { spell: 'elemental_wizards_rpg:aqua_springwater', name: '涌泉' },
      { spell: 'elemental_wizards_rpg:aqua_water_whip', name: '水鞭' },
      { spell: 'ysjxspells:abyss_blast_portal_water', name: '深渊水涌（海洋）' },
      { spell: 'ysjxspells:atomic_water', name: 'Atomic（海洋）' },
      { spell: 'ysjxspells:bingci1_water', name: '冰刺（初阶·海洋）' },
      { spell: 'ysjxspells:bingci2_water', name: '冰刺（升级·海洋）' },
      { spell: 'ysjxspells:cibeishexian_water', name: '慈悲射线（初阶·海洋）' },
      { spell: 'ysjxspells:cibeishexian2_water', name: '慈悲射线（升级·海洋）' },
      { spell: 'ysjxspells:cj_flame_strike_water', name: '烈焰打击（初阶·海洋）' },
      { spell: 'ysjxspells:cj_huanyingji_water', name: '幻影戟（初阶·海洋）' },
      { spell: 'ysjxspells:cj_luohunren_water', name: '落魂刃（初阶·海洋）' },
      { spell: 'ysjxspells:cj_water_wave_water', name: '海浪打击（初阶·海洋）' },
      { spell: 'ysjxspells:divine_gear_water', name: '神圣齿轮（海洋）' },
      { spell: 'ysjxspells:explosion_water', name: '爆裂魔法（海洋）' },
      { spell: 'ysjxspells:flame_strike_water', name: '烈焰打击（升级·海洋）' },
      { spell: 'ysjxspells:haiyangfeidan', name: '海洋飞弹' },
      { spell: 'ysjxspells:haiyangjiejie', name: '海洋结界' },
      { spell: 'ysjxspells:haiyangqianghua', name: '海洋强化' },
      { spell: 'ysjxspells:haiyangshuangfeidan_upgraded', name: '海洋飞弹（升级）' },
      { spell: 'ysjxspells:huanmo1_water', name: '唤魔尖牙（初阶·海洋）' },
      { spell: 'ysjxspells:huanmo2_water', name: '唤魔尖牙（中阶·海洋）' },
      { spell: 'ysjxspells:huanyingji_water', name: '幻影戟（海洋）' },
      { spell: 'ysjxspells:jianjizhedaodan_water', name: '歼击者导弹（海洋）' },
      { spell: 'ysjxspells:luohunren_water', name: '落魂刃（升级·海洋）' },
      { spell: 'ysjxspells:lvyanqiangxi_water', name: '绿焰强袭（海洋）' },
      { spell: 'ysjxspells:sandstorm_water', name: '沙暴缠绕（海洋）' },
      { spell: 'ysjxspells:scrap_drone_basic_water', name: '破片无人机（初阶·海洋）' },
      { spell: 'ysjxspells:scrap_drone_water', name: '破片无人机（海洋）' },
      { spell: 'ysjxspells:soul_flame_strike_water', name: '魂焰打击（海洋）' },
      { spell: 'ysjxspells:turret_basic_water', name: '圣城炮塔（初阶·海洋）' },
      { spell: 'ysjxspells:turret_water', name: '圣城炮塔（海洋）' },
      { spell: 'ysjxspells:water_wave_water', name: '海浪打击（海洋）' },
      { spell: 'ysjxspells:waterslash', name: '海洋斩击（初阶）' },
      { spell: 'ysjxspells:waterslash_2', name: '海洋斩击（中阶）' },
      { spell: 'ysjxspells:waterslash_3', name: '海洋斩击（高阶）' },
      { spell: 'ysjxspells:xiajiepaodan_water', name: '下界炮弹（海洋）' },
      { spell: 'ysjxspells:xianqudaodan_water', name: '先驱导弹（海洋）' },
      { spell: 'ysjxspells:xukongfuwen_water', name: '虚空符文（海洋）' },
      { spell: 'ysjxspells:xushici_water', name: '虚式茈（海洋）' },
      { spell: 'ysjxspells:yanmiechuansongmen_water', name: '湮灭传送门（海洋）' },
      { spell: 'ysjxspells:yanmiezhadan_water', name: '湮灭炸弹（海洋）' }
    ],

    earth: [
      { spell: 'elemental_wizards_rpg:terra_drip_circle', name: '大地法阵' },
      { spell: 'elemental_wizards_rpg:terra_earthquake', name: '地震' },
      { spell: 'elemental_wizards_rpg:terra_shattering_stone', name: '碎石迸裂' },
      { spell: 'elemental_wizards_rpg:terra_stone_flesh', name: '石化皮肤' },
      { spell: 'elemental_wizards_rpg:terra_stone_spear', name: '岩石长矛' },
      { spell: 'elemental_wizards_rpg:terra_stone_throw', name: '投石术' },
      { spell: 'ysjxspells:abyss_blast_portal_earth', name: '深渊水涌（大地）' },
      { spell: 'ysjxspells:atomic_earth', name: 'Atomic（大地）' },
      { spell: 'ysjxspells:bingci1_earth', name: '冰刺（初阶·大地）' },
      { spell: 'ysjxspells:bingci2_earth', name: '冰刺（升级·大地）' },
      { spell: 'ysjxspells:cibeishexian_earth', name: '慈悲射线（初阶·大地）' },
      { spell: 'ysjxspells:cibeishexian2_earth', name: '慈悲射线（升级·大地）' },
      { spell: 'ysjxspells:cj_flame_strike_earth', name: '烈焰打击（初阶·大地）' },
      { spell: 'ysjxspells:cj_huanyingji_earth', name: '幻影戟（初阶·大地）' },
      { spell: 'ysjxspells:cj_luohunren_earth', name: '落魂刃（初阶·大地）' },
      { spell: 'ysjxspells:cj_water_wave_earth', name: '海浪打击（初阶·大地）' },
      { spell: 'ysjxspells:dadiqianghua', name: '大地强化' },
      { spell: 'ysjxspells:divine_gear_earth', name: '神圣齿轮（大地）' },
      { spell: 'ysjxspells:dixin', name: '地心' },
      { spell: 'ysjxspells:explosion_earth', name: '爆裂魔法（大地）' },
      { spell: 'ysjxspells:flame_strike_earth', name: '烈焰打击（升级·大地）' },
      { spell: 'ysjxspells:huanmo1_earth', name: '唤魔尖牙（初阶·大地）' },
      { spell: 'ysjxspells:huanmo2_earth', name: '唤魔尖牙（中阶·大地）' },
      { spell: 'ysjxspells:huanyingji_earth', name: '幻影戟（大地）' },
      { spell: 'ysjxspells:jianjizhedaodan_earth', name: '歼击者导弹（大地）' },
      { spell: 'ysjxspells:liedichongji', name: '裂地冲击' },
      { spell: 'ysjxspells:luohunren_earth', name: '落魂刃（升级·大地）' },
      { spell: 'ysjxspells:lvyanqiangxi_earth', name: '绿焰强袭（大地）' },
      { spell: 'ysjxspells:sandstorm_earth', name: '沙暴缠绕（大地）' },
      { spell: 'ysjxspells:scrap_drone_basic_earth', name: '破片无人机（初阶·大地）' },
      { spell: 'ysjxspells:scrap_drone_earth', name: '破片无人机（大地）' },
      { spell: 'ysjxspells:shimao_upgraded', name: '石矛（升级）' },
      { spell: 'ysjxspells:soul_flame_strike_earth', name: '魂焰打击（大地）' },
      { spell: 'ysjxspells:terra_earthquake', name: '地震' },
      { spell: 'ysjxspells:tianxing', name: '天星' },
      { spell: 'ysjxspells:turret_basic_earth', name: '圣城炮塔（初阶·大地）' },
      { spell: 'ysjxspells:turret_earth', name: '圣城炮塔（大地）' },
      { spell: 'ysjxspells:water_wave_earth', name: '海浪打击（大地）' },
      { spell: 'ysjxspells:xiajiepaodan_earth', name: '下界炮弹（大地）' },
      { spell: 'ysjxspells:xianqudaodan_earth', name: '先驱导弹（大地）' },
      { spell: 'ysjxspells:xukongfuwen_earth', name: '虚空符文（大地）' },
      { spell: 'ysjxspells:xushici_earth', name: '虚式茈（大地）' },
      { spell: 'ysjxspells:yanmiechuansongmen_earth', name: '湮灭传送门（大地）' },
      { spell: 'ysjxspells:yanmiezhadan_earth', name: '湮灭炸弹（大地）' }
    ],

    air: [
      { spell: 'elemental_wizards_rpg:wind_aeroblast', name: '气流爆破' },
      { spell: 'elemental_wizards_rpg:wind_aeroburst', name: '气压爆发' },
      { spell: 'elemental_wizards_rpg:wind_air_cutter', name: '风刃' },
      { spell: 'elemental_wizards_rpg:wind_gust', name: '阵风' },
      { spell: 'elemental_wizards_rpg:wind_tornado', name: '龙卷风' },
      { spell: 'elemental_wizards_rpg:wind_updraft', name: '上升气流' },
      { spell: 'ysjxspells:abyss_blast_portal_air', name: '深渊水涌（空气）' },
      { spell: 'ysjxspells:airslash', name: '空气斩击（初阶）' },
      { spell: 'ysjxspells:airslash_2', name: '空气斩击（中阶）' },
      { spell: 'ysjxspells:airslash_3', name: '空气斩击（高阶）' },
      { spell: 'ysjxspells:atomic_air', name: 'Atomic（空气）' },
      { spell: 'ysjxspells:bingci1_air', name: '冰刺（初阶·空气）' },
      { spell: 'ysjxspells:bingci2_air', name: '冰刺（升级·空气）' },
      { spell: 'ysjxspells:cibeishexian_air', name: '慈悲射线（初阶·空气）' },
      { spell: 'ysjxspells:cibeishexian2_air', name: '慈悲射线（升级·空气）' },
      { spell: 'ysjxspells:cj_flame_strike_air', name: '烈焰打击（初阶·空气）' },
      { spell: 'ysjxspells:cj_huanyingji_air', name: '幻影戟（初阶·空气）' },
      { spell: 'ysjxspells:cj_luohunren_air', name: '落魂刃（初阶·空气）' },
      { spell: 'ysjxspells:cj_water_wave_air', name: '海浪打击（初阶·空气）' },
      { spell: 'ysjxspells:divine_gear_air', name: '神圣齿轮（空气）' },
      { spell: 'ysjxspells:explosion_air', name: '爆裂魔法（空气）' },
      { spell: 'ysjxspells:fengshenzhishi', name: '风神之诗' },
      { spell: 'ysjxspells:flame_strike_air', name: '烈焰打击（升级·空气）' },
      { spell: 'ysjxspells:huanmo1_air', name: '唤魔尖牙（初阶·空气）' },
      { spell: 'ysjxspells:huanmo2_air', name: '唤魔尖牙（中阶·空气）' },
      { spell: 'ysjxspells:huanyingji_air', name: '幻影戟（空气）' },
      { spell: 'ysjxspells:jianjizhedaodan_air', name: '歼击者导弹（空气）' },
      { spell: 'ysjxspells:kongqifeidan', name: '空气飞弹' },
      { spell: 'ysjxspells:kongqiqianghua', name: '空气强化' },
      { spell: 'ysjxspells:kongqishuangfeidan_upgraded', name: '空气飞弹（升级）' },
      { spell: 'ysjxspells:luohunren_air', name: '落魂刃（升级·空气）' },
      { spell: 'ysjxspells:lvyanqiangxi_air', name: '绿焰强袭（空气）' },
      { spell: 'ysjxspells:sandstorm_air', name: '沙暴缠绕（空气）' },
      { spell: 'ysjxspells:scrap_drone_air', name: '破片无人机（空气）' },
      { spell: 'ysjxspells:scrap_drone_basic_air', name: '破片无人机（初阶·空气）' },
      { spell: 'ysjxspells:soul_flame_strike_air', name: '魂焰打击（空气）' },
      { spell: 'ysjxspells:turret_air', name: '圣城炮塔（空气）' },
      { spell: 'ysjxspells:turret_basic_air', name: '圣城炮塔（初阶·空气）' },
      { spell: 'ysjxspells:water_wave_air', name: '海浪打击（空气）' },
      { spell: 'ysjxspells:xiajiepaodan_air', name: '下界炮弹（空气）' },
      { spell: 'ysjxspells:xianqudaodan_air', name: '先驱导弹（空气）' },
      { spell: 'ysjxspells:xukongfuwen_air', name: '虚空符文（空气）' },
      { spell: 'ysjxspells:xushici_air', name: '虚式茈（空气）' },
      { spell: 'ysjxspells:yanmiechuansongmen_air', name: '湮灭传送门（空气）' },
      { spell: 'ysjxspells:yanmiezhadan_air', name: '湮灭炸弹（空气）' }
    ],

    lightning: [
      { spell: 'ysjxspells:abyss_blast_portal_lightning', name: '深渊水涌（闪电）' },
      { spell: 'ysjxspells:atomic_lightning', name: 'Atomic（闪电）' },
      { spell: 'ysjxspells:bingci1_lightning', name: '冰刺（初阶·闪电）' },
      { spell: 'ysjxspells:bingci2_lightning', name: '冰刺（升级·闪电）' },
      { spell: 'ysjxspells:chesed_one_shot_vertical_ray', name: '赫塞德垂直雷击' },
      { spell: 'ysjxspells:cibeishexian_lightning', name: '慈悲射线（初阶·闪电）' },
      { spell: 'ysjxspells:cibeishexian2_lightning', name: '慈悲射线（升级·闪电）' },
      { spell: 'ysjxspells:cj_flame_strike_lightning', name: '烈焰打击（初阶·闪电）' },
      { spell: 'ysjxspells:cj_huanyingji_lightning', name: '幻影戟（初阶·闪电）' },
      { spell: 'ysjxspells:cj_luohunren_lightning', name: '落魂刃（初阶·闪电）' },
      { spell: 'ysjxspells:cj_water_wave_lightning', name: '海浪打击（初阶·闪电）' },
      { spell: 'ysjxspells:divine_gear_lightning', name: '神圣齿轮（闪电）' },
      { spell: 'ysjxspells:explosion_lightning', name: '爆裂魔法（闪电）' },
      { spell: 'ysjxspells:fcdc', name: '风驰电掣' },
      { spell: 'ysjxspells:fengbaozhaohuan', name: '风暴召唤' },
      { spell: 'ysjxspells:flame_strike_lightning', name: '烈焰打击（升级·闪电）' },
      { spell: 'ysjxspells:huanmo1_lightning', name: '唤魔尖牙（初阶·闪电）' },
      { spell: 'ysjxspells:huanmo2_lightning', name: '唤魔尖牙（中阶·闪电）' },
      { spell: 'ysjxspells:huanyingji_lightning', name: '幻影戟（闪电）' },
      { spell: 'ysjxspells:jianjizhedaodan_lightning', name: '歼击者导弹（闪电）' },
      { spell: 'ysjxspells:leiji', name: '雷击（升级）' },
      { spell: 'ysjxspells:leiji_basic', name: '雷击' },
      { spell: 'ysjxspells:leishenzhichui', name: '雷神之锤' },
      { spell: 'ysjxspells:liansuoshandian', name: '连锁闪电' },
      { spell: 'ysjxspells:lingyuleiji', name: '领域雷击' },
      { spell: 'ysjxspells:luohunren_lightning', name: '落魂刃（升级·闪电）' },
      { spell: 'ysjxspells:lvyanqiangxi_lightning', name: '绿焰强袭（闪电）' },
      { spell: 'ysjxspells:sandstorm_lightning', name: '沙暴缠绕（闪电）' },
      { spell: 'ysjxspells:scrap_drone_basic_lightning', name: '破片无人机（初阶·闪电）' },
      { spell: 'ysjxspells:scrap_drone_lightning', name: '破片无人机（闪电）' },
      { spell: 'ysjxspells:shandianqianghua', name: '闪电强化' },
      { spell: 'ysjxspells:soul_flame_strike_lightning', name: '魂焰打击（闪电）' },
      { spell: 'ysjxspells:turret_basic_lightning', name: '圣城炮塔（初阶·闪电）' },
      { spell: 'ysjxspells:turret_lightning', name: '圣城炮塔（闪电）' },
      { spell: 'ysjxspells:water_wave_lightning', name: '海浪打击（闪电）' },
      { spell: 'ysjxspells:xiajiepaodan_lightning', name: '下界炮弹（闪电）' },
      { spell: 'ysjxspells:xianqudaodan_lightning', name: '先驱导弹（闪电）' },
      { spell: 'ysjxspells:xukongfuwen_lightning', name: '虚空符文（闪电）' },
      { spell: 'ysjxspells:xushici_lightning', name: '虚式茈（闪电）' },
      { spell: 'ysjxspells:yanmiechuansongmen_lightning', name: '湮灭传送门（闪电）' },
      { spell: 'ysjxspells:yanmiezhadan_lightning', name: '湮灭炸弹（闪电）' }
    ],

    physical_ranged: [
      { spell: 'archers:barrage', name: '箭雨连射' },
      { spell: 'archers:entangling_roots', name: '缠绕根须' },
      { spell: 'archers:magic_arrow', name: '魔法箭' },
      { spell: 'lne_archers:rangers_focus', name: '游侠专注' },
      { spell: 'ysjxspells:abyss_blast_portal_ranged', name: '深渊水涌（游侠）' },
      { spell: 'ysjxspells:atomic_ranged', name: 'Atomic（游侠）' },
      { spell: 'ysjxspells:baozhajian', name: '爆炸箭' },
      { spell: 'ysjxspells:bingci1_ranged', name: '冰刺（初阶·游侠）' },
      { spell: 'ysjxspells:bingci2_ranged', name: '冰刺（升级·游侠）' },
      { spell: 'ysjxspells:cibeishexian_ranged', name: '慈悲射线（初阶·游侠）' },
      { spell: 'ysjxspells:cibeishexian2_ranged', name: '慈悲射线（升级·游侠）' },
      { spell: 'ysjxspells:cj_flame_strike_ranged', name: '烈焰打击（初阶·游侠）' },
      { spell: 'ysjxspells:divine_gear_ranged', name: '神圣齿轮（游侠）' },
      { spell: 'ysjxspells:explosion_ranged', name: '爆裂魔法（游侠）' },
      { spell: 'ysjxspells:flame_strike_ranged', name: '烈焰打击（升级·游侠）' },
      { spell: 'ysjxspells:huanmo1_ranged', name: '唤魔尖牙（初阶·游侠）' },
      { spell: 'ysjxspells:huanmo2_ranged', name: '唤魔尖牙（中阶·游侠）' },
      { spell: 'ysjxspells:jianjizhedaodan_ranged', name: '歼击者导弹（游侠）' },
      { spell: 'ysjxspells:jianyu', name: '箭雨' },
      { spell: 'ysjxspells:jianyu_gaojie', name: '灵魂箭雨' },
      { spell: 'ysjxspells:jingujian', name: '禁锢箭' },
      { spell: 'ysjxspells:lvyanqiangxi_ranged', name: '绿焰强袭（游侠）' },
      { spell: 'ysjxspells:sandstorm_ranged', name: '沙暴缠绕（游侠）' },
      { spell: 'ysjxspells:scrap_drone_basic_ranged', name: '破片无人机（初阶·游侠）' },
      { spell: 'ysjxspells:scrap_drone_ranged', name: '破片无人机（游侠）' },
      { spell: 'ysjxspells:soul_flame_strike_ranged', name: '魂焰打击（游侠）' },
      { spell: 'ysjxspells:turret_basic_ranged', name: '圣城炮塔（初阶·游侠）' },
      { spell: 'ysjxspells:turret_ranged', name: '圣城炮塔（游侠）' },
      { spell: 'ysjxspells:wanglingdun_ranged', name: '亡灵盾（游侠）' },
      { spell: 'ysjxspells:wangzhibaoku', name: '王之宝库（终极）' },
      { spell: 'ysjxspells:wangzhibaoku_1', name: '王之宝库（初阶）' },
      { spell: 'ysjxspells:wangzhibaoku_2', name: '王之宝库（升级）' },
      { spell: 'ysjxspells:wanjianqifa', name: '万箭齐发' },
      { spell: 'ysjxspells:water_wave_ranged', name: '海浪打击（游侠）' },
      { spell: 'ysjxspells:xiajiepaodan_ranged', name: '下界炮弹（游侠）' },
      { spell: 'ysjxspells:xianqudaodan_ranged', name: '先驱导弹（游侠）' },
      { spell: 'ysjxspells:xukongfuwen_ranged', name: '虚空符文（游侠）' },
      { spell: 'ysjxspells:xushici_ranged', name: '虚式茈（游侠）' },
      { spell: 'ysjxspells:yanmiechuansongmen_ranged', name: '湮灭传送门（游侠）' },
      { spell: 'ysjxspells:yanmiezhadan_ranged', name: '湮灭炸弹（游侠）' }
    ]
  };

  function getScrollItemId(spellId) {
    const overrideId = SCROLL_ITEM_ID_OVERRIDES[spellId];
    if (overrideId) {
      return overrideId;
    }

    const parts = spellId.split(':');
    const namespace = parts[0];
    const path = parts[1];

    if (namespace.indexOf('lne_') === 0) {
      return `lne_${path}_scroll`;
    }

    return `${path}_scroll`;
  }

  Object.keys(SPELLS_BY_SCHOOL).forEach(school => {
    SPELLS_BY_SCHOOL[school].forEach(spell => {
      const builder = event.create(getScrollItemId(spell.spell))
        .displayName(`§6${spell.name}卷轴`)
        .texture(SCROLL_TEXTURES[school])
        .maxStackSize(16);

      if (isEpicSpell(spell.spell)) {
        builder.rarity('epic');
      }
    });
  });
});
