package com.tnc.tnc.adventure;

import java.util.List;

/** Prices use copper. Produce is bought, never resold here: no buy/sell arbitrage. */
public final class ShopCatalog {
    public record Goods(String id,String name,String item,int count,int price,String detail){}
    public static final List<Goods> FURNITURE=List.of(
        new Goods("oak_chair","橡木靠背椅","model:chair",1,25,"木框与软垫，可坐。"),
        new Goods("blue_chair","海蓝扶手椅","model:armchair",1,45,"蓝色坐垫、双扶手，可坐。"),
        new Goods("dining_table","朝夕餐桌","model:table",1,60,"单格餐桌，可围坐用餐。"),
        new Goods("sofa","灯下双人沙发","model:sofa",1,120,"两格宽，两个座位。摆放前留出空间。"),
        new Goods("cabinet","归航储物柜","model:cabinet",1,90,"九格收纳，可右键使用。"),
        new Goods("bookcase","书风陈列架","model:bookcase",1,75,"木质分层展示架。"),
        new Goods("lamp","茶灯落地灯","model:lamp",1,55,"暖色灯罩，点亮房间。"),
        new Goods("bed","靛蓝床","minecraft:blue_bed",1,60,"凡家物语可识别的床；两人生活请备两张。"),
        new Goods("bookshelf","藏书柜","minecraft:bookshelf",1,50,"阅读与附魔空间。"),
        new Goods("carpet","海蓝地毯 ×8","minecraft:blue_carpet",8,16,"柔软地毯。"),
        new Goods("lantern","归航提灯","minecraft:lantern",1,20,"可悬挂。"),
        new Goods("flowerpot","窗边花盆","minecraft:flower_pot",1,10,"可种植花草。"),
        new Goods("oak_cabinet","橡木壁柜","farmersdelight:oak_cabinet",1,80,"农夫乐事原生壁柜。"),
        new Goods("spruce_cabinet","云杉壁柜","farmersdelight:spruce_cabinet",1,80,"农夫乐事原生壁柜。"),
        new Goods("candle","晚餐蜡烛 ×4","minecraft:candle",4,12,"摆好后用打火石点亮。"),
        new Goods("feast_table","团聚长桌","model:feast_table",1,150,"酒馆晚餐归档后开放；双格长桌，红色桌旗。"),
        new Goods("travel_lamp","远方航灯","model:travel_lamp",1,100,"远行见闻归档后开放；铜框蓝光，高架提灯。"),
        new Goods("memory_shelf","归处纪念柜","model:memory_shelf",1,130,"第一盏灯归档后开放；不对称陈列，六格储物。"));
    public static final List<Goods> PRODUCE=List.of(
        new Goods("wheat","小麦 ×16","minecraft:wheat",16,16,"农场主的基础收入。"),
        new Goods("carrot","胡萝卜 ×16","minecraft:carrot",16,12,"新鲜蔬菜。"),
        new Goods("potato","马铃薯 ×16","minecraft:potato",16,12,"新鲜蔬菜。"),
        new Goods("beetroot","甜菜根 ×16","minecraft:beetroot",16,16,"新鲜蔬菜。"),
        new Goods("pumpkin","南瓜 ×8","minecraft:pumpkin",8,24,"整颗收购。"),
        new Goods("melon","西瓜 ×8","minecraft:melon",8,24,"整颗收购。"),
        new Goods("berry","甜浆果 ×16","minecraft:sweet_berries",16,10,"野外采集也能出售。"),
        new Goods("egg","鸡蛋 ×8","minecraft:egg",8,16,"养鸡收入。"),
        new Goods("milk","牛奶桶 ×1","minecraft:milk_bucket",1,8,"收购牛奶，返还空桶。"),
        new Goods("wool","白色羊毛 ×8","minecraft:white_wool",8,24,"剪毛后羊仍能继续产毛。"),
        new Goods("beef","生牛肉 ×8","minecraft:beef",8,24,"牧场收获。"),
        new Goods("pork","生猪肉 ×8","minecraft:porkchop",8,24,"牧场收获。"),
        new Goods("chicken","生鸡肉 ×8","minecraft:chicken",8,16,"牧场收获。"),
        new Goods("mutton","生羊肉 ×8","minecraft:mutton",8,24,"牧场收获。"),
        new Goods("honey","蜂蜜瓶 ×4","minecraft:honey_bottle",4,16,"返还四个玻璃瓶。"),
        new Goods("tomato","番茄 ×16","farmersdelight:tomato",16,20,"农夫乐事作物。"),
        new Goods("cabbage","卷心菜 ×16","farmersdelight:cabbage",16,20,"农夫乐事作物。"),
        new Goods("onion","洋葱 ×16","farmersdelight:onion",16,20,"农夫乐事作物。"),
        new Goods("rice","稻米 ×16","farmersdelight:rice",16,20,"农夫乐事作物。"),
        new Goods("road_bell_ear","路铃麦穗 ×8","tnc:road_bell_ear",8,22,"旧驿道的麦香。可做归路铃饼，也可出售。"),
        new Goods("night_gourd","夜窗瓠 ×4","tnc:night_gourd",4,20,"暗处长成的暖色小瓠，适合夜行人的餐桌。"),
        new Goods("tide_reed_stem","听潮苇杆 ×8","tnc:tide_reed_stem",8,16,"水边生长的纹苇，可制纸、记录远行。"),
        new Goods("homeward_flower_petal","归巢花瓣 ×4","tnc:homeward_flower_petal",4,16,"真正远行归来才开放；可泡迎归茶，也可给朝夕商行。"),
        new Goods("warning_moss_flake","警路苔片 ×4","tnc:warning_moss_flake",4,20,"养在石墙上的警戒苔，可制作门前警灯。"),
        new Goods("resonant_fleece","响绒 ×4","tnc:resonant_fleece",4,36,"在草原或草甸寻找有青角铜铃的响铃羊，活着剪毛可重复获得。"),
        new Goods("hushcap_slice","缄声蕈片 ×4","tnc:hushcap_slice",4,24,"阴暗而安静的洞石上生长，可煮洞行蕈汤。"),
        new Goods("rainletter_berry","雨书莓果 ×8","tnc:rainletter_berry",8,24,"雨中结果，晴天可用清水瓶慢慢浇灌。"),
        new Goods("dawn_honey","晨蜜 ×8","tnc:dawn_honey",8,24,"晨晖盘葵的日照收获；也可做早餐。"),
        new Goods("hearth_pepper_fruit","暖椒 ×8","tnc:hearth_pepper_fruit",8,24,"炉边培育，料理与工坊都用得上。"),
        new Goods("mist_cotton_fiber","雾棉 ×8","tnc:mist_cotton_fiber",8,28,"湿润半阴环境培育，制布或出售。"),
        new Goods("stone_pattern_leaf","岩纹叶 ×8","tnc:stone_pattern_leaf",8,28,"岩函蕨的叶纹，可做署名调查页。"),
        new Goods("farlight_fruit","远照果 ×4","tnc:farlight_fruit",4,24,"夜里培育，可投掷照路或出售。"),
        new Goods("echo_bean_pod","回声豆 ×8","tnc:echo_bean_pod",8,32,"奏出三音，收获节律材料。"),
        new Goods("vine_sinew","藤筋 ×8","tnc:vine_sinew",8,24,"搭架培育，制绳或出售。"),
        new Goods("salt_ink","盐墨 ×4","tnc:salt_ink",4,28,"海岸菌类材料，可书写调查记录。"),
        new Goods("sail_fiber","帆纤维 ×8","tnc:sail_fiber",8,32,"高处迎风的魔法草收获。"),
        new Goods("sleep_leaf","静叶 ×4","tnc:sleep_leaf",4,24,"在床边好好休息后的收获。"),
        new Goods("shadow_silk","影绢 ×4","tnc:shadow_silk",4,32,"半阴花床的生活布料。"),
        new Goods("paper_bark","纸皮 ×8","tnc:paper_bark",8,20,"墨信树的可再生纸材。"),
        new Goods("rainproof_pod","防雨荚壳 ×4","tnc:rainproof_pod",4,28,"换羽荚产出，种匣与防雨用品。"),
        new Goods("honey_powder","蜜粉 ×8","tnc:honey_powder",8,28,"蜜簇需要附近蜜蜂授粉。"),
        new Goods("star_dew_fruit","星露果 ×4","tnc:star_dew_fruit",4,32,"直接吃可回复30真实魔力，也可交易。"),
        new Goods("dance_petal","舞瓣 ×4","tnc:dance_petal",4,24,"认主后会起舞的铃花产物。"),
        new Goods("sky_canopy_fiber","天幕纤维 ×4","tnc:sky_canopy_fiber",4,48,"四游戏日巨蔓成熟后持续采集。"),
        new Goods("stonebarrow_meat","石垒肉 ×8","tnc:stonebarrow_meat",8,32,"牧场料理的厚实肉材。"),
        new Goods("emberback_meat","暮炭肉 ×8","tnc:emberback_meat",8,36,"用暖饲料养出的肉材。"),
        new Goods("tideback_meat","潮背肉 ×8","tnc:tideback_meat",8,32,"水边养殖与潜水料理。"),
        new Goods("froststride_meat","银霜肉 ×8","tnc:froststride_meat",8,36,"寒地鸟肉，可做御寒烤串。"),
        new Goods("apiary_meat","蜂囊肉 ×8","tnc:apiary_meat",8,32,"魔法蛙的甜香肉材。"),
        new Goods("starfelt_meat","星苔肉 ×8","tnc:starfelt_meat",8,28,"兔群收获，可做远行卷。"),
        new Goods("froststride_egg","银霜卵 ×4","tnc:froststride_egg",4,24,"留养银霜步禽也能供货。"),
        new Goods("soft_down","软绒 ×4","tnc:soft_down",4,28,"星茸耳兔成年屠宰的柔茸副产物。"),
        new Goods("lantern_antler","暮灯落角 ×4","tnc:lantern_antler",4,40,"自然脱落，不必杀鹿。"),
        new Goods("flight_feather","邮羽 ×8","tnc:flight_feather",8,24,"留养邮羽鹭的羽材。"),
        new Goods("mirror_scale","镜鳞 ×4","tnc:mirror_scale",4,36,"夜蛾的周期鳞材，也可制聚光镜片。"),
        new Goods("runner_hide","负兽革 ×4","tnc:runner_hide",4,32,"牧场工具的皮材。"),
        new Goods("horn_powder","碗角粉 ×4","tnc:horn_powder",4,28,"保养犀角时取得，不必屠杀。"),
        new Goods("forage_paper_hide","浣兽纸皮 ×4","tnc:forage_paper_hide",4,28,"浣兽探索与留养材料。"),
        new Goods("lamp_wax","枕光灯蜡 ×4","tnc:lamp_wax",4,32,"养貂取蜡，添灯或出售。"),
        new Goods("dream_humus","梦腐质 ×4","tnc:dream_humus",4,20,"人工魔法土培育或异兽真实产物，可出售或留作工坊原料。"),
        new Goods("foldleaf_film","折叶膜 ×4","tnc:foldleaf_film",4,20,"人工魔法土培育或异兽真实产物，可出售或留作工坊原料。"),
        new Goods("shadow_hour_petal","影时瓣 ×4","tnc:shadow_hour_petal",4,20,"人工魔法土培育或异兽真实产物，可出售或留作工坊原料。"),
        new Goods("page_fern_fiber","旋页丝 ×4","tnc:page_fern_fiber",4,20,"人工魔法土培育或异兽真实产物，可出售或留作工坊原料。"),
        new Goods("cycle_sandgrain","昼夜砂 ×4","tnc:cycle_sandgrain",4,20,"人工魔法土培育或异兽真实产物，可出售或留作工坊原料。"),
        new Goods("dewgrass_thread","露丝 ×4","tnc:dewgrass_thread",4,20,"人工魔法土培育或异兽真实产物，可出售或留作工坊原料。"),
        new Goods("prism_crown_petal","虹折片 ×4","tnc:prism_crown_petal",4,20,"人工魔法土培育或异兽真实产物，可出售或留作工坊原料。"),
        new Goods("ore_dream_flake","矿眠屑 ×4","tnc:ore_dream_flake",4,20,"人工魔法土培育或异兽真实产物，可出售或留作工坊原料。"),
        new Goods("storm_crown_tip","雷冠尖 ×4","tnc:storm_crown_tip",4,20,"人工魔法土培育或异兽真实产物，可出售或留作工坊原料。"),
        new Goods("prism_horn_shard","彩角碎 ×4","tnc:prism_horn_shard",4,20,"人工魔法土培育或异兽真实产物，可出售或留作工坊原料。"),
        new Goods("sand_otter_fiber","砂獭纤维 ×4","tnc:sand_otter_fiber",4,20,"人工魔法土培育或异兽真实产物，可出售或留作工坊原料。"));

    public static Goods find(List<Goods> list,String id){return list.stream().filter(g->g.id().equals(id)).findFirst().orElse(null);}
    public static int quota(int level){return level>=45?2000:level>=20?1000:500;}
}
