package com.tnc.tnc.adventure;

import com.tnc.tnc.home.*;
import net.minecraft.core.BlockPos;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.*;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.*;
import net.minecraftforge.gametest.*;

@GameTestHolder("tnc") @PrefixGameTestTemplate(false)
public final class TownStoryGameTests {
    private static net.minecraft.server.level.ServerPlayer atGuild(GameTestHelper h){var p=AdventureGameTests.player(h);var pos=h.absolutePos(new BlockPos(3,3,3));p.teleportTo(pos.getX()+.5,pos.getY(),pos.getZ()+.5);var npc=com.tnc.tnc.npc.TNNpcs.SERVICE_NPC.get().create(h.getLevel());npc.role("guild");npc.moveTo(p.position());h.getLevel().addFreshEntity(npc);AdventureService.profile(p).registered=true;return p;}
    @GameTest(template="building_test_empty",batch="town_stories",timeoutTicks=40)
    public static void supperPaysEachChapterOnceAndPreservesSpecialIngredients(GameTestHelper h){
        var p=atGuild(h);var account=AdventureService.profile(p);TownStories.advance(p,"supper");var named=new ItemStack(Items.WHEAT,8);named.setHoverName(net.minecraft.network.chat.Component.literal("纪念麦穗"));p.getInventory().setItem(0,named);p.getInventory().setItem(1,new ItemStack(Items.CARROT,8));TownStories.advance(p,"supper");h.assertTrue(account.coins()==0&&p.getInventory().getItem(1).getCount()==8,"Named ingredients do not satisfy or consume ordinary delivery");
        p.getInventory().setItem(2,new ItemStack(Items.WHEAT,8));TownStories.advance(p,"supper");h.assertTrue(account.coins()==25&&TownStories.record(p,"supper").getInt("Stage")==2&&p.getInventory().getItem(0).getCount()==8,"One chapter paid, keepsake retained");TownStories.advance(p,"supper");h.assertTrue(account.coins()==25,"Repeat packet cannot repeat chapter reward");
        p.getInventory().setItem(1,new ItemStack(Items.COOKED_BEEF,4));p.getInventory().setItem(2,new ItemStack(Items.BAKED_POTATO,4));TownStories.advance(p,"supper");h.assertTrue(account.coins()==60,"Second distinct chapter delivers");TownStories.rememberVisit(p,"lin");TownStories.rememberVisit(p,"lin");TownStories.rememberVisit(p,"qiao");p.getInventory().setItem(1,new ItemStack(Items.MILK_BUCKET));p.getInventory().setItem(2,new ItemStack(Items.EGG,4));TownStories.advance(p,"supper");
        h.assertTrue(account.coins()==120&&TownStories.complete(p,"supper")&&TownStories.unlocked(p,"feast_table"),"Dinner ending unlocks real shop item");h.assertTrue(p.getInventory().items.stream().anyMatch(s->s.is(Items.BUCKET))&&p.getInventory().items.stream().filter(s->s.hasTag()&&s.getTag().contains("TncTownStory")).count()==1,"Milk bucket returned and one unique keepsake");TownStories.advance(p,"supper");h.assertTrue(account.coins()==120,"Ending not repeatable");
        var saved=AdventureSavedData.load(AdventureSavedData.get(p.server).save(new CompoundTag()));h.assertTrue(saved.housing.getCompound("TownStories").getCompound(p.getUUID().toString()).getCompound("supper").getInt("Stage")==4,"Story completion persists");h.succeed();
    }
    @GameTest(template="building_test_empty",batch="town_stories",timeoutTicks=40)
    public static void uniqueRewardsFullBagAndRemotePacketsDoNotConsumeAnything(GameTestHelper h){
        var p=atGuild(h);var r=TownStories.record(p,"supper");r.putInt("Stage",3);TownStories.rememberVisit(p,"lin");TownStories.rememberVisit(p,"qiao");for(int i=0;i<36;i++)p.getInventory().setItem(i,new ItemStack(Items.STONE,64));p.getInventory().setItem(0,new ItemStack(Items.MILK_BUCKET));p.getInventory().setItem(1,new ItemStack(Items.EGG,8));TownStories.advance(p,"supper");h.assertTrue(r.getInt("Stage")==3&&p.getInventory().getItem(0).is(Items.MILK_BUCKET)&&p.getInventory().getItem(1).getCount()==8&&AdventureService.profile(p).coins()==0,"Bucket and unique page cannot fit: all ingredients preserved");
        p.teleportTo(p.getX()+100,p.getY(),p.getZ());AdventureService.action(p,AdventurePackets.Action.STORY_ADVANCE,"supper");h.assertTrue(r.getInt("Stage")==3&&p.getInventory().getItem(0).is(Items.MILK_BUCKET),"Remote network cannot deliver story");h.succeed();
    }
    @GameTest(template="building_test_empty",batch="town_stories",timeoutTicks=40)
    public static void journeyCountsOnlyAfterAcceptanceAndRequiresThreeUniqueBiomesAndNeighbors(GameTestHelper h){
        var p=atGuild(h);TownStories.recordBiome(p,"minecraft:plains");h.assertTrue(TownStories.record(p,"journey").getList("Biomes",8).isEmpty(),"No retroactive exploration");TownStories.advance(p,"journey");TownStories.recordBiome(p,"minecraft:plains");TownStories.recordBiome(p,"minecraft:plains");TownStories.advance(p,"journey");h.assertTrue(TownStories.record(p,"journey").getInt("Stage")==1,"Duplicates cannot satisfy three biomes");TownStories.recordBiome(p,"minecraft:forest");TownStories.recordBiome(p,"minecraft:desert");TownStories.advance(p,"journey");p.getInventory().setItem(0,new ItemStack(Items.PAPER,3));p.getInventory().setItem(1,new ItemStack(Items.INK_SAC));TownStories.advance(p,"journey");TownStories.rememberVisit(p,"lin");TownStories.rememberVisit(p,"qiao");TownStories.advance(p,"journey");h.assertTrue(!TownStories.complete(p,"journey"),"Third chapter requires three distinct listeners");TownStories.rememberVisit(p,"lan");TownStories.advance(p,"journey");h.assertTrue(TownStories.unlocked(p,"travel_lamp")&&AdventureService.profile(p).coins()==130,"Quiet journey finishes without boss kills");h.succeed();
    }
    @GameTest(template="building_test_empty",batch="town_stories",timeoutTicks=40)
    public static void homeStoryChecksOwnedBoundsActualFurnitureAndAFullNight(GameTestHelper h){
        var p=atGuild(h);var store=AdventureSavedData.get(p.server);var saved=store.housing.copy();try{for(var plot:PlotCatalog.ALL)store.housing.remove(plot.id());TownStories.advance(p,"home");TownStories.advance(p,"home");h.assertTrue(TownStories.record(p,"home").getInt("Stage")==1,"Home milestone alone does not replace ownership");
            var plot=PlotCatalog.find("sweet_cottage");var origin=h.absolutePos(new BlockPos(1,2,1)).subtract(plot.min());var home=new CompoundTag();home.putUUID("Owner",p.getUUID());home.putLong("Origin",origin.asLong());store.housing.put(plot.id(),home);TownStories.advance(p,"home");var pos=origin.offset(plot.min()).offset(2,1,2);var level=h.getLevel();level.setBlock(pos,Blocks.BLUE_BED.defaultBlockState().setValue(BedBlock.PART,net.minecraft.world.level.block.state.properties.BedPart.HEAD),18);level.setBlock(pos.offset(2,0,0),Blocks.LANTERN.defaultBlockState(),18);
            if(net.minecraftforge.fml.ModList.get().isLoaded("immersive_furniture")){var block=net.minecraftforge.registries.ForgeRegistries.BLOCKS.getValue(net.minecraft.resources.ResourceLocation.parse("immersive_furniture:furniture"));level.setBlock(pos.offset(3,0,0),block.defaultBlockState(),18);TownStories.advance(p,"home");h.assertTrue(TownStories.record(p,"home").getInt("Stage")==3,"Bed light and actual furniture in owned bounds advance");TownStories.rememberRest(p,pos.offset(100,0,0),100);TownStories.rememberRest(p,pos,99);h.assertTrue(!TownStories.record(p,"home").getBoolean("Rested"),"Foreign bed or interrupted sleep rejected");TownStories.rememberRest(p,pos,100);TownStories.advance(p,"home");h.assertTrue(TownStories.complete(p,"home")&&TownStories.unlocked(p,"memory_shelf"),"Actual own-home night completes final chapter");}h.succeed();
        }finally{store.housing=saved;store.setDirty();}
    }
    @GameTest(template="building_test_empty",batch="town_stories",timeoutTicks=40)
    public static void recommendationIsSharedPersistsAndCannotRerollOnClockRollback(GameTestHelper h){
        var p=AdventureGameTests.player(h);var store=AdventureSavedData.get(p.server);var original=store.housing.getCompound("MarketDay").copy();try{store.housing.remove("MarketDay");long day=System.currentTimeMillis()/86_400_000L;var t=TownMarketDay.state(p.server,day*86_400_000L);String featured=t.getString("Featured");h.assertTrue(TownMarketDay.state(p.server,(day-1)*86_400_000L).getString("Featured").equals(featured),"Clock rollback cannot choose another crop");// Keep the real recommendation/rollback checks above; use a registered vanilla product for the sale fixture, since the dev server does not load every food mod.
            featured="wheat";t.putString("Featured",featured);var goods=ShopCatalog.find(ShopCatalog.PRODUCE,featured);long before=AdventureService.profile(p).coins();p.getInventory().setItem(0,new ItemStack(net.minecraftforge.registries.ForgeRegistries.ITEMS.getValue(net.minecraft.resources.ResourceLocation.parse(goods.item())),goods.count()));String sale=ShopService.sell(p,featured);h.assertTrue(AdventureService.profile(p).coins()-before==goods.price()*3/2,"Featured produce actually pays 150 percent: "+sale);h.assertTrue(ShopService.snapshot(p).getCompound("SalePrices").getInt(featured)==goods.price()*3/2,"Displayed price equals server transaction price");
            var copy=AdventureSavedData.load(store.save(new CompoundTag()));h.assertTrue(copy.housing.getCompound("MarketDay").getString("Featured").equals(featured),"Town-wide day survives restart");h.assertTrue(!TownStories.unlocked(p,"feast_table")&&ShopService.buy(p,"feast_table").contains("先完成"),"Direct purchase cannot bypass story unlock");h.succeed();
        }finally{store.housing.put("MarketDay",original);store.setDirty();}
    }
    @GameTest(template="building_test_empty",batch="native_sleep_story",timeoutTicks=40)
    public static void nativeWakeUpEventRecordsDawnButRejectsManualExit(GameTestHelper h)throws Exception{
        var p=AdventureGameTests.player(h);var store=AdventureSavedData.get(p.server);var saved=store.housing.copy();try{for(var plot:PlotCatalog.ALL)store.housing.remove(plot.id());var plot=PlotCatalog.find("sweet_cottage");var bed=h.absolutePos(new BlockPos(3,3,3));var origin=bed.subtract(plot.min()).offset(-1,0,-1);h.setBlock(new BlockPos(3,3,3),Blocks.BLUE_BED);var home=new CompoundTag();home.putUUID("Owner",p.getUUID());home.putLong("Origin",origin.asLong());store.housing.put(plot.id(),home);TownStories.record(p,"home").putInt("Stage",3);
            var timer=net.minecraft.world.entity.player.Player.class.getDeclaredField("sleepCounter");timer.setAccessible(true);p.startSleeping(bed);timer.setInt(p,100);p.stopSleepInBed(true,true);h.assertTrue(!TownStories.record(p,"home").getBoolean("Rested"),"Native manual wake does not finish overnight chapter");p.startSleeping(bed);timer.setInt(p,100);p.stopSleepInBed(false,false);h.assertTrue(TownStories.record(p,"home").getBoolean("Rested"),"Native server dawn wake fires real Forge event before sleeping position is cleared");h.succeed();
        }finally{store.housing=saved;store.setDirty();}
    }
    @GameTest(template="building_test_empty",batch="explore_story",timeoutTicks=40)
    public static void realExploreTickRejectsIslandRimAndRecordsActualOutsideBiome(GameTestHelper h)throws Exception{
        var l=h.getLevel();var old=com.tnc.tnc.world.SkyIslandSavedData.get(l);var cls=com.tnc.tnc.world.SkyIslandSavedData.class;var load=cls.getDeclaredMethod("load",CompoundTag.class);load.setAccessible(true);var origin=h.absolutePos(new BlockPos(1,3,1)).offset(-501,-100,-200);var fixture=old.save(new CompoundTag());fixture.putString("Phase","COMPLETE");fixture.putBoolean("LayoutReady",true);fixture.putInt("OriginX",origin.getX());fixture.putInt("OriginY",origin.getY());fixture.putInt("OriginZ",origin.getZ());l.getDataStorage().set("tnc_sky_island_v5",(net.minecraft.world.level.saveddata.SavedData)load.invoke(null,fixture));
        try{var p=AdventureGameTests.player(h);p.tickCount=100;TownStories.record(p,"journey").putInt("Stage",1);p.setPos(origin.getX()+501,origin.getY()+100,origin.getZ()+200);TownStories.explore(new net.minecraftforge.event.TickEvent.PlayerTickEvent(net.minecraftforge.event.TickEvent.Phase.END,p));h.assertTrue(TownStories.record(p,"journey").getList("Biomes",8).isEmpty(),"520-wide island rim is still town, not remote exploration");p.setPos(origin.getX()+530,origin.getY()+100,origin.getZ()+200);TownStories.explore(new net.minecraftforge.event.TickEvent.PlayerTickEvent(net.minecraftforge.event.TickEvent.Phase.END,p));h.assertTrue(TownStories.record(p,"journey").getList("Biomes",8).size()==1,"Outside tick records actual registered biome, no client-provided id");h.succeed();}finally{l.getDataStorage().set("tnc_sky_island_v5",old);}
    }
}
