from pathlib import Path
import json,base64,nbtlib,argparse
root=Path(__file__).resolve().parents[1]
parser=argparse.ArgumentParser(description='Build an offline atlas from tracked town assets.')
parser.add_argument('--output',type=Path,default=root/'docs/art')
parser.add_argument('--world',type=Path,help='Optional world directory to read the sky-island origin.')
args=parser.parse_args();output=args.output;output.mkdir(parents=True,exist_ok=True)
rows=json.loads((root/'docs/art/rouchnao-building-index.json').read_text('utf8'))
plots=json.loads((root/'src/main/resources/data/tnc/housing/catalog.json').read_text('utf8'))['plots']
labels=json.loads((root/'src/main/resources/data/tnc/housing/labels.json').read_text('utf8'))
names={int(l['number']):l['name'] for l in labels if l['id'].startswith('building_')}
for r in rows:
 r['number']=str(r['number']).zfill(2);r['name']=names[int(r['number'])];r['kind']='服务岗位' if int(r['number']) in [19,28,29,32,34,41] else '居民住宅' if int(r['number']) in [23,31,37] else '公共保留';r['price']=0;r['detail']=r['proposal']
 p=next((p for p in plots if p['number']==str(int(r['number']))),None)
 if p:r.update(p);r['kind']='可购买住宅';r['number']=p['number']
 if r['number']=='32':r['detail']='朝夕商行 · 织夏。家具与家饰购买、农畜产品收购，一楼店员在室内，二楼可布置样板间。'
 if r['number']=='19':r['detail']='归航银行 · 米洛。钱袋、存款、现实日息、贷款、五套房源和农牧地，办事柜台保留可站位空间。'
 if r['number']=='41':r['detail']='Self 与原剧情、协会接待员艾琳、Bountiful 原生委托栏。重点做公共长桌、吧台、客人席位和委托栏通路。'
for p in plots:
 if p['kind']=='HOME':continue
 rows.append(dict(p,x=(p['min'][0]+p['max'][0])/2,z=(p['min'][2]+p['max'][2])/2,kind='可购买土地'))
mapdata=base64.b64encode((root/'docs/art/sky-island-user-map-20260929.png').read_bytes()).decode()
origin=[-36,90,524] # Recorded origin of the author's current world; editable in the atlas.
if args.world:
 world=nbtlib.load(args.world/'data/tnc_sky_island_v5.dat')['data']
 origin=[int(world.get('OriginX',0)),int(world.get('OriginY',90)),int(world.get('OriginZ',0))]
page='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RouchNao · 小镇规划图</title>
<style>
:root{--ink:#243b3c;--paper:#efe7d5;--gold:#b98637;--blue:#4b93bd;--green:#488068}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:15px "Microsoft YaHei",sans-serif}header{padding:34px 42px 26px;border-bottom:1px solid #cabfa9;display:flex;align-items:end;justify-content:space-between;gap:25px}h1{font:44px Georgia,"SimSun",serif;margin:5px 0 0;letter-spacing:1px}small{letter-spacing:3px;color:#677873}header p{max-width:470px;line-height:1.8;margin:0}main{display:grid;grid-template-columns:minmax(550px,1fr) 330px;max-width:1500px;margin:auto}.map-shell{padding:26px}.filters{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:16px}button{font:inherit;cursor:pointer;border:1px solid #9aab9e;background:transparent;color:var(--ink);padding:8px 13px}button:hover,button.active{background:var(--ink);color:var(--paper)}.map{position:relative;width:100%;aspect-ratio:1173/1022;background:#456649;overflow:hidden;box-shadow:0 16px 36px #263c3625}.map>img{width:100%;height:100%;object-fit:contain;display:block;image-rendering:pixelated}.pin{position:absolute;transform:translate(-50%,-50%);border:2px solid #f8edd6;box-shadow:0 2px 5px #0008;border-radius:50%;width:29px;height:29px;padding:0;font-size:12px;font-weight:bold;background:#334846;color:white;z-index:2}.pin[data-kind="服务岗位"]{background:#9e6724}.pin[data-kind="可购买住宅"]{background:#266c95}.pin[data-kind="居民住宅"]{background:#397357}.pin[data-kind="可购买土地"]{border-radius:3px;background:#325e55;width:36px}.pin.selected{background:#fff;color:#183836;outline:3px solid #f0bf6a;z-index:3}.plot{position:absolute;border:2px dashed #f5db94;background:#b9d18322;pointer-events:none}.legend{font-size:12px;margin-top:14px;line-height:1.8;color:#61716c}aside{border-left:1px solid #cabfa9;padding:28px 26px;position:sticky;top:0;height:100vh;overflow:auto}.eyebrow{font-size:12px;letter-spacing:2px;color:#77837c}h2{font:27px "SimSun",serif;margin:9px 0 18px}aside p{line-height:1.8}dl{border-top:1px solid #cbbda1;padding-top:16px}dt{font-size:12px;color:#77837c;margin-top:14px}dd{margin:5px 0;font-family:Georgia,"Microsoft YaHei",serif;font-size:19px}.note{font-size:13px;line-height:1.8;border-top:1px solid #cbbda1;padding-top:20px;margin-top:22px}input{width:76px;border:1px solid #a8b1a5;background:#f8f1e2;padding:7px;font-size:13px;color:var(--ink)}.origin{display:flex;gap:5px;margin-top:8px}.home-list{display:flex;flex-wrap:wrap;gap:6px;margin-top:18px}.home-list button{font-size:12px;padding:5px 8px}footer{padding:18px 42px;border-top:1px solid #cabfa9;font-size:12px;color:#61716c}@media(max-width:950px){main{display:flex;flex-direction:column}.map-shell{padding:15px}aside{position:static;height:auto;border-left:0;border-top:1px solid #cabfa9}header{display:block;padding:22px}header p{margin-top:15px}h1{font-size:32px}.pin{width:23px;height:23px;font-size:10px}}
</style>
<header><div><small>ROUCHNAO · TOWN ATLAS</small><h1>归处，从一扇门开始。</h1></div><p>魔法师会远行，也会回家。点击门牌查看房源、服务与居民住宅；四块农田、一片牧场，给种养和日常经营留一席之地。</p></header>
<main><section class="map-shell"><div class="filters"><button class="active" data-filter="全部">全部门牌</button><button data-filter="服务岗位">服务岗位</button><button data-filter="可购买住宅">五套房源</button><button data-filter="居民住宅">居民住宅</button><button data-filter="可购买土地">农田与牧场</button></div><div class="map" id="map"><img alt="作者提供的天空岛俯视截图" src="data:image/png;base64,MAPDATA"></div><p class="legend">金色：银行、商行与公共服务　蓝色：可购买住宅　绿色：居民住宅　虚线：农牧地的水平边界<br>18 / 20 是同一训练场的两个入口。编号沿用原地图。图上边界只用于规划，游戏权限以银行目录中的三维范围为准。</p></section>
<aside><div class="eyebrow" id="type">可购买住宅</div><h2 id="name"></h2><p id="detail"></p><dl id="facts"></dl><div class="home-list" id="homes"></div><div class="note" id="brief"></div><div class="note">世界原点（已填入「新的世界」记录，可改成其他测试世界）<div class="origin"><input aria-label="原点X" id="ox"><input aria-label="原点Y" id="oy"><input aria-label="原点Z" id="oz"></div><p>游戏中优先右键米洛，在「房子 / 土地」选择去看房。不要把这里的原点直接用于不同存档。</p></div></aside></main><footer>2026.10.01 · RouchNao 内饰协作与房源核对图 · 已售住宅的后续装修不得被整岛模板覆盖。</footer>
<script>
const rows=ROWS,origin=ORIGIN;const map=document.getElementById('map');let selected=rows.find(r=>r.number==='26');
['ox','oy','oz'].forEach((id,i)=>{document.getElementById(id).value=origin[i];document.getElementById(id).addEventListener('input',()=>select(selected));});
const point=(x,z)=>[(x*3-280)/1173*100,(z*3-290)/1022*100];
rows.forEach(r=>{if(r.kind==='可购买土地'){let [x,z]=point(r.min[0],r.min[2]),[xx,zz]=point(r.max[0]+1,r.max[2]+1);let a=document.createElement('div');a.className='plot';Object.assign(a.style,{left:x+'%',top:z+'%',width:(xx-x)+'%',height:(zz-z)+'%'});a.dataset.kind=r.kind;map.appendChild(a);}let b=document.createElement('button');b.className='pin';b.dataset.kind=r.kind;b.textContent=r.number;b.title=r.number+' · '+r.name;b.setAttribute('aria-label',b.title);let [x,z]=point(r.x,r.z);if(r.number==='18')x-=1.8;if(r.number==='20')x+=1.8;b.style.left=x+'%';b.style.top=z+'%';b.onclick=()=>select(r);map.appendChild(b);r.button=b;});
function select(r){selected=r;rows.forEach(a=>a.button.classList.toggle('selected',a===r));document.getElementById('type').textContent=r.kind;document.getElementById('name').textContent=r.number+' · '+r.name;document.getElementById('detail').textContent=r.detail;let ori=['ox','oy','oz'].map(id=>Number(document.getElementById(id).value)||0);const coord=p=>p.map((v,i)=>v+ori[i]).join(' / ');let facts='<dt>入口坐标 X / Y / Z</dt><dd>'+coord(r.entry)+'</dd>';if(r.price){facts+='<dt>全款价格</dt><dd>'+r.price+' 铜</dd>';if(r.kind==='可购买住宅')facts+='<dt>分期购房</dt><dd>首付 '+(r.price*.3)+' 铜</dd><dt>随后 10 期</dt><dd>每期 '+(Math.floor(Math.round(r.price*.7*1.1)/10))+(Math.round(r.price*.7*1.1)%10?'–'+Math.ceil(Math.round(r.price*.7*1.1)/10):'')+' 铜 / 期</dd>';facts+='<dt>产权边界（含高度）</dt><dd style="font:13px Microsoft YaHei">'+coord(r.min)+'<br>至 '+coord(r.max)+'</dd>';}document.getElementById('facts').innerHTML=facts;document.getElementById('brief').textContent=r.kind==='可购买住宅'?'交付标准：空屋。墙、屋顶、楼梯和门保留；室内家居交付时清理。玩家买入后边界内可挖可放。箱内物品或现场有改动时银行会停止出售，保留现场。':r.kind==='可购买土地'?'原状土地交付：坡度、树木由主人整理。地界标签用于辨认四角。无需租金；同类土地每人先各一块。陌生人不能收割或操作私有地的牲畜。':r.kind==='居民住宅'?'保留两张普通 Minecraft 床及床旁两格高活动空间。六位居民使用凡家物语原生交往、婚姻、生育与家谱；不要把常驻居民床换成仅有装饰外观的家具床。':'内饰优先保留店员与楼梯通路；公共柜台不出售。茶灯会馆玩法后续制作，其他未指定公共建筑先保留。';}
rows.filter(r=>r.kind==='可购买住宅').forEach(r=>{let b=document.createElement('button');b.textContent=r.number+'号';b.onclick=()=>select(r);document.getElementById('homes').appendChild(b);});document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(a=>a.classList.toggle('active',a===b));document.querySelectorAll('.pin,.plot').forEach(a=>a.hidden=b.dataset.filter!=='全部'&&a.dataset.kind!==b.dataset.filter);});select(selected);
</script></html>'''
page=page.replace('MAPDATA',mapdata).replace('ROWS',json.dumps(rows,ensure_ascii=False)).replace('ORIGIN',json.dumps(origin))
(output/'RouchNao-小镇编号地图.html').write_text(page,encoding='utf8')
(root/'work/rouchnao-map-metadata.json').write_text(json.dumps(dict(origin=origin,rows=rows),ensure_ascii=False,indent=2),encoding='utf8')
print('Atlas generated; origin:',origin,'locations:',len(rows))
