# -*- coding: utf-8 -*-
"""
gen_dragon_model.py -- a RIGGED giant dragon (Bedrock geo + 256x256 texture).

Author 2026-10-02: "生成一个巨龙的模型，我要骨骼的" -> the deliverable is the RIG (bones
with joints in the right places) plus a workable texture; animations come later.

Conventions (same as every other model in this project):
    1 unit = 1/16 block, +Y up, feet at y=0, model faces -Z (verify with tools/face_uv_check.py).
    No cube rotations and no `mirror` flags -> the right half is generated by negating x,
    which is exact and cannot silently break.

SIZE (giant, as asked): snout to tail-tip ~12.1 blocks, wingspan ~11.8 blocks,
                        standing height ~4.7 blocks (horn tips).

RIG (36 bones; every joint is a real bone so it can be posed/animated):
    root
      body            chest + belly plates + 4 spine spikes
        neck1 > neck2 > neck3 > head
                                   jaw, hornL, hornR
        wingL1 > wingL2 > wingL3 > wingL4      (leading-edge strut + membrane plate each)
        wingR1 > wingR2 > wingR3 > wingR4
        legFL1 > legFL2 > pawFL                (front leg: shoulder / knee / paw+claws)
        legFR1 > legFR2 > pawFR
      hips            pelvis + 2 spikes
        tail1 > tail2 > tail3 > tail4 > tail5 > tailFin
        legBL1 > legBL2 > pawBL                (hind leg)
        legBR1 > legBR2 > pawBR

TEXTURE 256x256, Bedrock **box UV** (the only convention this project has proven in game):
    every cube gets its own rectangle of (2d+2w) x (d+h) pixels, packed top-left to
    bottom-right, and that rectangle is painted with its material's pattern. UV values in
    the json are plain texture pixels (same as gothic_priest/yan/etc).
ASCII only.  Usage:  python tools/gen_dragon_model.py
"""
import json
import math
import os
import random

from PIL import Image

MODID, NAME = "tnc", "dragon"
# 512x512：这条龙 40 个方块、翼展 11.8 格，box-UV 每块自己要 (2d+2w)x(d+h) 这么大一块贴图 ✗
# （256 装不下：实测需要 ~55k 像素，加上货架式装箱的浪费就超了 ✓）
TEX = 512
MARGIN = 2                      # gap between packed rectangles (bleeding guard)

# ------------------------------------------------------------------ palette
# 想要火龙 / 暗龙 / 金龙：改这 6 行就行（都是 (r, g, b) 基调）✓
DORSAL = (26, 62, 74)           # 背脊深青
DORSAL_HI = (58, 128, 138)      # 鳞片高光
LIMB = (34, 78, 88)             # 四肢/脖子略亮
BELLY = (198, 220, 228)         # 腹甲浅银蓝
MEMBRANE = (18, 54, 68)         # 翼膜
BONE = (232, 224, 204)          # 角 / 牙 / 爪根
EYE = (255, 186, 60)            # 眼睛琥珀


def clamp(v):
    return max(0, min(255, int(v)))


def shade(c, k):
    return (clamp(c[0] * k), clamp(c[1] * k), clamp(c[2] * k), 255)


# ------------------------------------------------------------------ materials
# 每个 painter 拿到 (img, box, size)：box = 该方块在贴图里那块矩形 (x0, y0, w, h)，
# size = 方块尺寸 (w, h, d)。Bedrock 的 box-UV 排布是**固定**的 ⇒ 可以按"哪块是朝上的面"
# 来上色：朝上压暗（背脊）、朝下提亮（腹部）✓ —— 这样一条龙从上面看是深色、从下面看是浅色 ✓
#
# box-UV 排布（矩形内，单位=像素）：
#     up   = (d,       0, w, d)
#     down = (d + w,   0, w, d)
#     side strip = (0, d) .. (2d + 2w, d + h)   ->  -X | -Z | +X | +Z
def _tone(img, box, rect, k, jitter=0, rng=None):
    x0, y0, w, h = box
    rx, ry, rw, rh = rect
    for y in range(ry, ry + rh):
        for x in range(rx, rx + rw):
            if 0 <= x < w and 0 <= y < h:
                p = img.getpixel((x0 + x, y0 + y))
                j = rng.randint(-jitter, jitter) if (rng and jitter) else 0
                img.putpixel((x0 + x, y0 + y), (clamp(p[0] * k + j), clamp(p[1] * k + j),
                                                clamp(p[2] * k + j), 255))


def paint_scales(img, box, size, base, hi, period=8, seed=1, dorsal=0.66, ventral=1.45):
    """tileable scale rows + dark back / pale underside (box-UV aware)"""
    x0, y0, w, h = box
    cw, ch, cd = size
    rng = random.Random(seed)
    for y in range(h):
        row = y // period
        off = (period // 2) if row % 2 else 0
        for x in range(w):
            phase = (x + off) % period
            edge = phase in (0,) or y % period == 0
            c = hi if (phase < 2 and y % period < period - 1) else base
            if edge:
                c = tuple(int(v * 0.62) for v in base)
            j = rng.randint(-6, 6)
            img.putpixel((x0 + x, y0 + y), (clamp(c[0] + j), clamp(c[1] + j), clamp(c[2] + j), 255))
    _tone(img, box, (cd, 0, cw, cd), dorsal, 5, rng)              # up   -> 背脊深色
    _tone(img, box, (cd + cw, 0, cw, cd), ventral, 5, rng)        # down -> 腹部浅色


def paint_belly(img, box, base, seed=2):
    """horizontal belly plates with a bright rim"""
    x0, y0, w, h = box
    rng = random.Random(seed)
    for y in range(h):
        band = y % 6
        for x in range(w):
            k = 1.0 if band < 4 else 1.12
            if band == 5:
                k = 0.80
            j = rng.randint(-5, 5)
            img.putpixel((x0 + x, y0 + y), (clamp(base[0] * k + j), clamp(base[1] * k + j),
                                            clamp(base[2] * k + j), 255))


def paint_membrane(img, box, base, seed=3):
    """wing membrane: dark sheet + lighter veins fanning out of the top-left corner"""
    x0, y0, w, h = box
    rng = random.Random(seed)
    span = max(w, h)
    for y in range(h):
        for x in range(w):
            d = math.hypot(x, y)
            vein = abs(math.sin(math.atan2(y, x) * 7.0)) if d > 2 else 0.0
            k = 0.82 + 0.55 * (d / float(span)) + (0.5 if vein > 0.94 else 0.0)
            j = rng.randint(-4, 4)
            img.putpixel((x0 + x, y0 + y), (clamp(base[0] * k + j), clamp(base[1] * k + j),
                                            clamp(base[2] * k + j), 255))


def paint_bone(img, box, base, seed=4):
    x0, y0, w, h = box
    rng = random.Random(seed)
    for y in range(h):
        for x in range(w):
            ring = (y // 3) % 2
            k = 0.92 + 0.10 * ring
            j = rng.randint(-7, 7)
            img.putpixel((x0 + x, y0 + y), (clamp(base[0] * k + j), clamp(base[1] * k + j),
                                            clamp(base[2] * k + j), 255))


def paint_claw(img, box, base, seed=5):
    x0, y0, w, h = box
    for y in range(h):
        for x in range(w):
            k = 0.55 + 0.55 * (x / float(max(1, w - 1)))
            img.putpixel((x0 + x, y0 + y), shade((44, 38, 34), k))


def paint_eye(img, box, base, seed=6):
    x0, y0, w, h = box
    for y in range(h):
        for x in range(w):
            cx, cy = (w - 1) / 2.0, (h - 1) / 2.0
            slit = abs(x - cx) < 0.9 and abs(y - cy) < h * 0.38
            if slit:
                img.putpixel((x0 + x, y0 + y), (24, 14, 8, 255))
            else:
                d = math.hypot((x - cx) / max(1.0, cx), (y - cy) / max(1.0, cy))
                k = max(0.35, 1.10 - 0.75 * d)
                img.putpixel((x0 + x, y0 + y), shade(base, k))


MATERIALS = {
    "scale": lambda img, box, size: paint_scales(img, box, size, DORSAL, DORSAL_HI, 8, 11),
    "limb": lambda img, box, size: paint_scales(img, box, size, LIMB, DORSAL_HI, 7, 12, 0.78, 1.30),
    "belly": lambda img, box, size: paint_belly(img, box, BELLY),
    "membrane": lambda img, box, size: paint_membrane(img, box, MEMBRANE),
    "bone": lambda img, box, size: paint_bone(img, box, BONE),
    "claw": lambda img, box, size: paint_claw(img, box, (44, 38, 34)),
    "eye": lambda img, box, size: paint_eye(img, box, EYE),
}


# ------------------------------------------------------------------ model
def cube(cx, cy, cz, w, h, d, mat):
    """cube given by its CENTRE (x is symmetric around 0 because w is even)"""
    assert w % 2 == 0 and h % 2 == 0 and d % 2 == 0, "keep sizes even: %s" % ((w, h, d),)
    assert cx == 0 or True
    return {"c": (cx, cy, cz), "s": (w, h, d), "mat": mat}


def left_bones():
    """every bone that lives on the LEFT (+X) side; the right side is mirrored below."""
    b = []

    def B(name, parent, pivot, cubes):
        b.append({"name": name, "parent": parent, "pivot": list(pivot), "cubes": cubes})

    # ---- 躯干 ----
    B("body", "root", (0, 34, -12), [
        cube(0, 35, -12, 18, 20, 34, "scale"),        # chest
        cube(0, 25, -10, 14, 6, 30, "belly"),         # belly plates
        cube(0, 47, -24, 2, 6, 6, "bone"),            # spine spikes
        cube(0, 48, -14, 2, 8, 6, "bone"),
        cube(0, 48, -4, 2, 8, 6, "bone"),
        cube(0, 47, 6, 2, 6, 6, "bone"),
    ])
    B("hips", "body", (0, 34, 14), [
        cube(0, 34, 16, 16, 18, 24, "scale"),
        cube(0, 44, 12, 2, 6, 6, "bone"),
        cube(0, 44, 22, 2, 4, 6, "bone"),
    ])

    # ---- 脖子 / 头 ----
    B("neck1", "body", (0, 40, -26), [cube(0, 41, -32, 12, 14, 16, "limb")])
    B("neck2", "neck1", (0, 46, -38), [cube(0, 47, -44, 10, 12, 16, "limb")])
    B("neck3", "neck2", (0, 51, -50), [cube(0, 52, -56, 10, 12, 14, "limb")])
    B("head", "neck3", (0, 54, -62), [
        cube(0, 55, -66, 14, 12, 16, "scale"),        # skull
        cube(0, 53, -78, 10, 8, 14, "scale"),         # snout
        cube(0, 61, -66, 12, 4, 14, "bone"),          # brow / crest
        cube(7, 57, -72, 2, 4, 4, "eye"),             # eye (left)
        cube(3, 53, -80, 2, 4, 2, "bone"),            # fangs
        cube(3, 53, -76, 2, 4, 2, "bone"),
    ])
    B("jaw", "head", (0, 51, -70), [cube(0, 48, -78, 8, 6, 14, "limb")])
    B("hornL", "head", (5, 60, -62), [
        cube(6, 64, -60, 4, 12, 4, "bone"),
        cube(6, 72, -56, 2, 6, 4, "bone"),
    ])

    # ---- 翅膀（4 段：臂 / 肘 / 腕 / 指尖 + 每段一片膜）----
    B("wingL1", "body", (8, 42, -22), [
        cube(20, 44, -24, 24, 6, 6, "limb"),          # leading edge
        cube(22, 32, -20, 26, 22, 2, "membrane"),
    ])
    B("wingL2", "wingL1", (32, 44, -24), [
        cube(44, 45, -22, 24, 6, 6, "limb"),
        cube(46, 30, -18, 26, 24, 2, "membrane"),
    ])
    B("wingL3", "wingL2", (56, 44, -22), [
        cube(66, 46, -20, 20, 6, 6, "limb"),
        cube(67, 32, -16, 22, 20, 2, "membrane"),
    ])
    B("wingL4", "wingL3", (76, 46, -20), [
        cube(84, 47, -16, 16, 4, 4, "bone"),          # wing claw
        cube(85, 36, -13, 18, 16, 2, "membrane"),
    ])

    # ---- 前腿 ----
    B("legFL1", "body", (9, 28, -18), [cube(9, 22, -18, 8, 14, 10, "limb")])
    B("legFL2", "legFL1", (9, 15, -18), [cube(9, 9, -18, 6, 12, 8, "limb")])
    B("pawFL", "legFL2", (9, 3, -18), [
        cube(9, 2, -20, 8, 4, 12, "limb"),
        cube(6, 1, -27, 2, 2, 4, "claw"),
        cube(9, 1, -28, 2, 2, 4, "claw"),
        cube(12, 1, -27, 2, 2, 4, "claw"),
    ])

    # ---- 后腿 ----
    B("legBL1", "hips", (9, 28, 18), [cube(9, 22, 20, 8, 14, 10, "limb")])
    B("legBL2", "legBL1", (9, 15, 20), [cube(9, 9, 20, 6, 12, 10, "limb")])
    B("pawBL", "legBL2", (9, 3, 20), [
        cube(9, 2, 18, 8, 4, 12, "limb"),
        cube(6, 1, 9, 2, 2, 4, "claw"),
        cube(9, 1, 8, 2, 2, 4, "claw"),
        cube(12, 1, 9, 2, 2, 4, "claw"),
    ])

    # ---- 尾巴 ----
    B("tail1", "hips", (0, 36, 28), [cube(0, 36, 36, 12, 14, 18, "scale")])
    B("tail2", "tail1", (0, 36, 45), [cube(0, 36, 54, 10, 12, 18, "scale")])
    B("tail3", "tail2", (0, 36, 63), [cube(0, 36, 70, 8, 10, 16, "scale")])
    B("tail4", "tail3", (0, 36, 78), [cube(0, 36, 84, 6, 8, 14, "scale")])
    B("tail5", "tail4", (0, 36, 91), [cube(0, 36, 96, 6, 6, 12, "scale")])
    B("tailFin", "tail5", (0, 36, 102), [
        cube(0, 36, 105, 2, 18, 8, "membrane"),
        cube(5, 36, 104, 8, 12, 2, "membrane"),
    ])
    return b


def mirrored(bones):
    """right half: negate x on pivots and cube centres (exact, no `mirror` flag)"""
    out = []
    for bone in bones:
        out.append(bone)
        if "L" in bone["name"]:
            twin = {
                "name": bone["name"].replace("L", "R"),
                "parent": bone["parent"].replace("L", "R"),
                "pivot": [-bone["pivot"][0], bone["pivot"][1], bone["pivot"][2]],
                "cubes": [dict(c, c=(-c["c"][0], c["c"][1], c["c"][2])) for c in bone["cubes"]],
            }
            out.append(twin)
    return out


class Packer:
    """shelf packer: every cube asks for a (2d+2w) x (d+h) rectangle (Bedrock box UV)"""

    def __init__(self, size):
        self.size = size
        self.x = MARGIN
        self.y = MARGIN
        self.row_h = 0
        self.used = 0

    def alloc(self, w, h):
        if self.x + w + MARGIN > self.size:
            self.x = MARGIN
            self.y += self.row_h + MARGIN
            self.row_h = 0
        if self.y + h + MARGIN > self.size:
            raise RuntimeError("texture atlas %dx%d is too small" % (self.size, self.size))
        box = (self.x, self.y, w, h)
        self.x += w + MARGIN
        self.row_h = max(self.row_h, h)
        self.used += w * h
        return box


def build():
    bones = mirrored(left_bones())
    bones.insert(0, {"name": "root", "parent": None, "pivot": [0, 0, 0], "cubes": []})

    packer = Packer(TEX)
    img = Image.new("RGBA", (TEX, TEX), (0, 0, 0, 0))
    out_bones = []
    for bone in bones:
        cubes = []
        for c in bone["cubes"]:
            cx, cy, cz = c["c"]
            w, h, d = c["s"]
            box = packer.alloc(2 * d + 2 * w, d + h)
            MATERIALS[c["mat"]](img, box, (w, h, d))
            cubes.append({
                "origin": [cx - w // 2, cy - h // 2, cz - d // 2],
                "size": [w, h, d],
                "uv": [box[0], box[1]],
            })
        entry = {"name": bone["name"], "pivot": bone["pivot"]}
        if bone["parent"]:
            entry["parent"] = bone["parent"]
        if cubes:
            entry["cubes"] = cubes
        out_bones.append(entry)

    geo = {
        "format_version": "1.12.0",
        "minecraft:geometry": [{
            "description": {
                "identifier": "geometry.%s.%s" % (MODID, NAME),
                "texture_width": TEX, "texture_height": TEX,
                "visible_bounds_width": 16, "visible_bounds_height": 7,
                "visible_bounds_offset": [0, 3, 0],
            },
            "bones": out_bones,
        }],
    }
    report = {
        "bones": len(out_bones),
        "cubes": sum(len(b.get("cubes", [])) for b in out_bones),
        "atlas_used": packer.used,
        "atlas_total": TEX * TEX,
        "atlas_pct": round(100.0 * packer.used / (TEX * TEX), 1),
    }
    return geo, img, report


def main():
    repo = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    gp = os.path.join(repo, "src", "main", "resources", "assets", "tnc", "geo", "entity", NAME + ".geo.json")
    tp = os.path.join(repo, "src", "main", "resources", "assets", "tnc", "textures", "entity", NAME + "_bedrock.png")
    pp = os.path.join(repo, "docs", "previews", NAME + "_texture.png")
    for p in (gp, tp, pp):
        os.makedirs(os.path.dirname(p), exist_ok=True)
    geo, tex, rep = build()
    with open(gp, "w", encoding="utf-8", newline="\n") as f:
        json.dump(geo, f, indent=2, ensure_ascii=False)
        f.write("\n")
    tex.save(tp)
    tex.resize((TEX * 2, TEX * 2), Image.NEAREST).save(pp)
    print("geo     -> %s" % os.path.relpath(gp, repo))
    print("texture -> %s" % os.path.relpath(tp, repo))
    print("preview -> %s" % os.path.relpath(pp, repo))
    print("bones=%d cubes=%d  atlas %d/%d px (%.1f%%)"
          % (rep["bones"], rep["cubes"], rep["atlas_used"], rep["atlas_total"], rep["atlas_pct"]))


if __name__ == "__main__":
    main()
