"""Precise migration of existing ecology paths; never edits a world/template."""
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
def edit(path, old, new):
    p=ROOT/path; text=p.read_text(encoding='utf-8')
    if new and new in text:return
    if old not in text:
        if not new or new in text:return
        raise ValueError(f'missing anchor: {path}: {old[:80]}')
    p.write_text(text.replace(old,new),encoding='utf-8')
J='src/main/java/com/tnc/tnc/'
edit(J+'life/pasture/PastureRegistry.java','new ManaBottleItem(24)','new ManaBottleItem(100)')
edit(J+'life/pasture/PastureRegistry.java','new ManaBottleItem(72)','new ManaBottleItem(400)')
edit(J+'life/pasture/PastureRegistry.java','ITEMS.put("pasture_cage",new PastureCageItem());','ITEMS.put("pasture_cage",new PastureCageItem(1));ITEMS.put("radiant_cage",new PastureCageItem(2));ITEMS.put("star_cage",new PastureCageItem(3));')
edit(J+'life/pasture/PastureBottleLedger.java','int cap=t.getInt("Capacity")==72?72:24;','int cap=Math.max(1,Math.min(400,t.getInt("Capacity")));')
edit(J+'life/pasture/ManaBottleItem.java','Math.min(24,space)','Math.min(100,space)')
edit(J+'life/pasture/ManaBottleItem.java','Math.min(24,magic.getMaxMana()-magic.getMana())','Math.min(100,magic.getMaxMana()-magic.getMana())')
edit(J+'production/MagicForgeBlockEntity.java','MAX_CHARGE = 200','MAX_CHARGE = 2000')
edit(J+'production/client/MagicForgeScreen.java','112*menu.charge()/200','112*menu.charge()/MagicForgeBlockEntity.MAX_CHARGE')
edit(J+'production/client/MagicForgeScreen.java','menu.charge()+"/200"','menu.charge()+"/"+MagicForgeBlockEntity.MAX_CHARGE')
edit(J+'life/botanical/BotanicalPlantEntity.java','if(!wild) {','if(!wild) {\n            if(!com.tnc.tnc.life.routes.MagicSoilBlock.isSoil(l.getBlockState(worldPosition.below())))return "需要魔法土或土源";\n            if(!com.tnc.tnc.life.routes.MagicSoilBlock.irrigated(l,worldPosition.below()))return "缺少八格内的流动魔力：保留植株，暂停生长";')
edit(J+'life/botanical/BotanicalPlantEntity.java','owner=species()==BotanicalSpecies.DANCE_BELL?null:id;','owner=id;')
edit(J+'life/botanical/BotanicalPlantEntity.java','notes=Math.min(3,notes+1);changed();','notes=Math.min(3,notes+1);getPersistentData().putInt("DistinctNotes",getPersistentData().getInt("DistinctNotes")|(1<<pattern));changed();')
edit(J+'life/botanical/BotanicalBlock.java','var held=player.getItemInHand(hand);','var held=player.getItemInHand(hand);\n        if(com.tnc.tnc.life.routes.RouteSources.feedBotanical(be,sp,held))return InteractionResult.CONSUME;\n        if(s.getValue(AGE)==3&&held.is(Items.SHEARS)){Block.popResource(l,p,new ItemStack(BotanicalContent.SEEDS.get(species.id)));be.harvest();return InteractionResult.CONSUME;}')
edit(J+'life/botanical/BotanicalBlock.java','if(be.wild&&s.getValue(AGE)==3){','if(s.getValue(AGE)==3){')
edit(J+'life/botanical/BotanicalBlock.java','else if(++be.harvests%3==0)','else if(++be.harvests>0)')
edit(J+'life/botanical/BotanicalBlock.java','be.harvest();l.playSound','com.tnc.tnc.life.routes.RouteProgress.award(sp,"harvest/"+species.id);be.harvest();l.playSound')
edit(J+'life/botanical/BotanicalProductItem.java','if(id.equals("stone_pattern_leaf")','var plant=com.tnc.tnc.life.routes.RoutePlanting.plantFruit(id,c);if(plant!=InteractionResult.PASS)return plant;\n        if(id.equals("stone_pattern_leaf")')
edit(J+'life/ecology/VerdantVeinBlockEntity.java','else be.mana=Math.min(40,be.mana+1);','else if(l.getGameTime()%40==0)be.mana=Math.min(40,be.mana+1);')
edit(J+'life/ecology/VerdantVeinBlockEntity.java','return prunes%3==0;','return true;')
edit(J+'life/pasture/PastureSpecies.java','"凝露浮鲸"','"蓄魔鲸"')
edit(J+'life/pasture/PastureSpecies.java','s("pillowlight_marten"','s("prismatic_antelope","曳彩角羚",Role.ELEMENT,Habitat.LAND,Items.HONEY_BOTTLE,3,3,2,"prism_horn_shard",1,1.0f,1.6f),\n        s("drumbelly_otter","鼓腹砂獭",Role.ELEMENT,Habitat.LAND,Items.CARROT,2,2,2,"sand_otter_fiber",1,0.95f,0.8f),\n        s("pillowlight_marten"')
edit(J+'life/pasture/PastureRegistry.java','"stonebarrow_meat",','"prism_horn_shard","sand_otter_fiber","stonebarrow_meat",')
edit(J+'life/pasture/PastureAnimal.java','case"dewbound_whale"->96;case"wirecall_lizard"->100;','case"dewbound_whale"->16000;case"wirecall_lizard"->2400;')
edit(J+'life/pasture/PastureAnimal.java','Math.min(96,resource+48)','Math.min(16000,resource+120)')
edit(J+'life/pasture/PastureAnimal.java','resource+amount>100','resource+amount>2400')
edit(J+'life/pasture/PastureAnimal.java','Math.min(24,Math.min(resource,requested))','Math.min(100,Math.min(resource,requested))')
edit(J+'life/pasture/PastureAnimal.java','if(!(level() instanceof ServerLevel server))return;lastActive','if(!(level() instanceof ServerLevel server))return;keepInsideHome();lastActive')
edit(J+'life/pasture/PastureAnimal.java','tickProduction(server);','tickProduction(server);tickManaPower(server);')
edit(J+'life/pasture/PastureAnimal.java','if(s.isThundering()&&s.isRainingAt(blockPosition()))resource=Math.min(100,resource+5);','')
edit(J+'life/pasture/PastureAnimal.java','resource-=50;id="storm_crystal";','resource-=50;id="storm_crystal";')
edit(J+'life/pasture/PastureAnimal.java','ItemStack result=new ItemStack(PastureRegistry.item(id),','getPersistentData().putInt("WorkMana",0);getPersistentData().putInt("ManaFoodBudget",0);\n        ItemStack result=new ItemStack(PastureRegistry.item(id),')
edit(J+'life/pasture/PastureAnimal.java','helped=true;}\n            else if(state','helped=true;}\n            else if(state')
edit(J+'life/pasture/PastureFlight.java','random.nextInt(17)-8','random.nextInt(animal.hasHome()?7:17)-(animal.hasHome()?3:8)')
edit(J+'life/pasture/PastureFlight.java','y=Mth.clamp(y,','if(animal.hasHome())y=Mth.clamp(y,anchor.getY()+1,anchor.getY()+7-(int)Math.ceil(animal.getBbHeight()));\n                y=Mth.clamp(y,')
edit(J+'life/UncommonMagicPlants.java','builder.add(AGE, QUIET);','builder.add(AGE, QUIET, com.tnc.tnc.life.routes.RoutePlantBlock.WILD);')
edit(J+'life/UncommonMagicPlants.java','builder.add(AGE, WET);','builder.add(AGE, WET, com.tnc.tnc.life.routes.RoutePlantBlock.WILD);')
edit(J+'life/UncommonMagicPlants.java','.setValue(QUIET, 0));','.setValue(QUIET, 0).setValue(com.tnc.tnc.life.routes.RoutePlantBlock.WILD,false));')
edit(J+'life/UncommonMagicPlants.java','.setValue(WET, false));','.setValue(WET, false).setValue(com.tnc.tnc.life.routes.RoutePlantBlock.WILD,false));')
edit(J+'life/OriginalCrops.java','block.defaultBlockState().setValue(UncommonMagicPlants.HushcapBlock.AGE, 3)','block.defaultBlockState().setValue(com.tnc.tnc.life.routes.RoutePlantBlock.WILD,true).setValue(UncommonMagicPlants.HushcapBlock.AGE, 3)')
edit(J+'life/OriginalCrops.java','block.defaultBlockState().setValue(UncommonMagicPlants.RainletterBlock.AGE, 3)','block.defaultBlockState().setValue(com.tnc.tnc.life.routes.RoutePlantBlock.WILD,true).setValue(UncommonMagicPlants.RainletterBlock.AGE, 3)')
print('Integrated existing lifecycle interfaces.')
