package com.tnc.tnc.life.botanical;

import com.tnc.tnc.adventure.AdventureGameTests;
import com.tnc.tnc.magic.MagicStone;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.phys.*;
import net.minecraftforge.gametest.*;
import java.util.UUID;

@GameTestHolder("tnc") @PrefixGameTestTemplate(false)
public final class BotanicalGameTests {
    @GameTest(template="building_test_empty",batch="botanical_permissions",timeoutTicks=30)
    public static void ownedPreparedFieldGrowsTreeAndVineOfflineButPublicTownAndOtherOwnersCannot(GameTestHelper h)throws Exception{
        var l=h.getLevel();var owner=AdventureGameTests.player(h);var field=com.tnc.tnc.home.PlotCatalog.find("field_01");var treePos=h.absolutePos(new BlockPos(1,3,1));var vinePos=treePos.west();var publicPos=treePos.east(3);
        var origin=treePos.subtract(new BlockPos(field.max().getX()-1,95,field.max().getZ()-1));var records=com.tnc.tnc.adventure.AdventureSavedData.get(l.getServer());var savedHousing=records.housing.copy();var savedSky=com.tnc.tnc.world.SkyIslandSavedData.get(l);var skyTag=savedSky.save(new CompoundTag());skyTag.putString("Phase","COMPLETE");skyTag.putBoolean("LayoutReady",true);skyTag.putInt("OriginX",origin.getX());skyTag.putInt("OriginY",origin.getY());skyTag.putInt("OriginZ",origin.getZ());var load=com.tnc.tnc.world.SkyIslandSavedData.class.getDeclaredMethod("load",CompoundTag.class);load.setAccessible(true);
        var grow=BotanicalPlantEntity.class.getDeclaredMethod("updateSegments",net.minecraft.server.level.ServerLevel.class);grow.setAccessible(true);var home=new CompoundTag();home.putUUID("Owner",owner.getUUID());home.putLong("Origin",origin.asLong());home.putBoolean("Preparing",false);records.housing.put(field.id(),home);l.getDataStorage().set("tnc_sky_island_v5",(net.minecraft.world.level.saveddata.SavedData)load.invoke(null,skyTag));
        try{
            for(var pos:java.util.List.of(treePos,vinePos,publicPos)){l.setBlockAndUpdate(pos.below(),Blocks.DIRT.defaultBlockState());for(int y=0;y<4;y++)l.setBlockAndUpdate(pos.above(y),Blocks.AIR.defaultBlockState());}
            l.setBlockAndUpdate(treePos,BotanicalContent.BLOCKS.get("paper_tree").defaultBlockState());l.setBlockAndUpdate(vinePos,BotanicalContent.BLOCKS.get("ladder_vine").defaultBlockState());l.setBlockAndUpdate(publicPos,BotanicalContent.BLOCKS.get("paper_tree").defaultBlockState());
            var tree=(BotanicalPlantEntity)l.getBlockEntity(treePos);var vine=(BotanicalPlantEntity)l.getBlockEntity(vinePos);var townTree=(BotanicalPlantEntity)l.getBlockEntity(publicPos);for(var root:java.util.List.of(tree,vine,townTree)){root.owner=owner.getUUID();root.bookStudied=true;root.growth=root.species().firstTicks;}
            h.assertTrue(l.getServer().getPlayerList().getPlayer(owner.getUUID())==null,"Fixture exercises the saved owner's offline FakePlayer permission path");
            grow.invoke(tree,l);grow.invoke(vine,l);h.assertTrue(l.getBlockState(treePos.above(2)).is(BotanicalContent.PAPER_SEGMENT)&&l.getBlockState(vinePos.above(3)).is(BotanicalContent.VINE_SEGMENT),"Actual tree and climbable vine extend inside their owner's purchased prepared field even while that owner is offline");
            h.assertTrue(com.tnc.tnc.home.TownProtection.town(l,publicPos)&&com.tnc.tnc.home.HousingService.ownedAt(l,publicPos)==null,"Public fixture is a real protected town position outside purchased land");grow.invoke(townTree,l);h.assertTrue(l.getBlockState(publicPos.above()).isAir(),"An owned root cannot extend into public town blocks");townTree.owner=null;grow.invoke(townTree,l);h.assertTrue(l.getBlockState(publicPos.above()).isAir(),"A wild root cannot bypass public town protection");
            for(int y=1;y<4;y++)l.setBlockAndUpdate(treePos.above(y),Blocks.AIR.defaultBlockState());tree.owner=UUID.randomUUID();grow.invoke(tree,l);h.assertTrue(l.getBlockState(treePos.above()).isAir(),"Another planter cannot grow through a purchased field they do not own");tree.owner=owner.getUUID();home.putBoolean("Preparing",true);grow.invoke(tree,l);h.assertTrue(l.getBlockState(treePos.above()).isAir(),"A field still being prepared cannot grow extra geometry");home.putBoolean("Preparing",false);l.setBlockAndUpdate(treePos.above(),Blocks.STONE.defaultBlockState());grow.invoke(tree,l);h.assertTrue(l.getBlockState(treePos.above()).is(Blocks.STONE),"A player replacement is preserved instead of overwritten by growth");h.succeed();
        }finally{for(var pos:java.util.List.of(treePos,vinePos,publicPos))for(int y=0;y<4;y++)l.setBlockAndUpdate(pos.above(y),Blocks.AIR.defaultBlockState());records.housing=savedHousing;l.getDataStorage().set("tnc_sky_island_v5",savedSky);}
    }
    @GameTest(template="building_test_empty",batch="botanical",timeoutTicks=30)
    public static void lotusSeedNormalAirUsePlantsAboveWaterAndKeepsTheWaterSource(GameTestHelper h){var l=h.getLevel();var water=h.absolutePos(new BlockPos(2,2,2));l.setBlockAndUpdate(water.below(),Blocks.CLAY.defaultBlockState());l.setBlockAndUpdate(water,Blocks.WATER.defaultBlockState());l.setBlockAndUpdate(water.above(),Blocks.AIR.defaultBlockState());var p=AdventureGameTests.player(h);p.setPos(water.getX()+.5,water.getY()+2,water.getZ()+.5);p.setXRot(90);p.setYRot(0);var seed=new ItemStack(BotanicalContent.SEEDS.get("mirror_lotus"),2);p.getInventory().setItem(0,seed);seed.getItem().use(l,p,InteractionHand.MAIN_HAND);h.assertTrue(l.getBlockState(water).is(Blocks.WATER)&&l.getFluidState(water).isSource(),"Normal right-click planting leaves original source water intact");h.assertTrue(l.getBlockState(water.above()).is(BotanicalContent.BLOCKS.get("mirror_lotus"))&&seed.getCount()==1,"Normal Item.use raycast actually plants one lotus in the water-surface air");h.assertTrue(l.getBlockEntity(water.above()) instanceof BotanicalPlantEntity be&&p.getUUID().equals(be.owner),"The normal placement path preserves planter UUID");h.succeed();}
    @GameTest(template="building_test_empty",batch="botanical",timeoutTicks=30)
    public static void nineteenSeparateRootsPersistTheirOwnGrowthAndEventEvidence(GameTestHelper h){
        UUID owner=UUID.randomUUID();h.assertTrue(BotanicalContent.BLOCKS.size()==19&&BotanicalContent.SEEDS.size()==19,"Nineteen independently registered new species exist");
        for(var species:BotanicalSpecies.values()){var state=BotanicalContent.BLOCKS.get(species.id).defaultBlockState();var be=new BotanicalPlantEntity(BlockPos.ZERO,state);var tag=be.saveWithoutMetadata();tag.putUUID("Owner",owner);tag.putInt("Growth",1234);tag.putInt("Notes",3);tag.putInt("Pollinations",2);tag.putBoolean("Ready",true);tag.putInt("Pattern",7);be.load(tag);var restored=new BotanicalPlantEntity(BlockPos.ZERO,state);restored.load(be.saveWithoutMetadata());h.assertTrue(restored.growth==1234&&owner.equals(restored.owner)&&restored.notes==3&&restored.pollinations==2&&restored.ready&&restored.pattern==7,"Saved root retains actual progress and event evidence: "+species.id);h.assertTrue(BotanicalContent.PRODUCTS.get(species.product)!=null,"Harvest has its registered real product: "+species.id);}
        h.succeed();
    }
    @GameTest(template="building_test_empty",batch="botanical",timeoutTicks=50)
    public static void anEmptyColdFurnaceDoesNotGrowPeppersAndReloadCannotInventEvents(GameTestHelper h){var l=h.getLevel();var p=h.absolutePos(new BlockPos(2,3,2));l.setBlockAndUpdate(p.below(),Blocks.DIRT.defaultBlockState());l.setBlockAndUpdate(p,BotanicalContent.BLOCKS.get("hearth_pepper").defaultBlockState());l.setBlockAndUpdate(p.east(),Blocks.FURNACE.defaultBlockState());var be=(BotanicalPlantEntity)l.getBlockEntity(p);be.growth=1200;var tag=be.saveWithoutMetadata();tag.putLong("LastActiveTick",l.getGameTime()-96000);tag.putBoolean("WasGrowing",true);be.load(tag);be.onLoad();h.assertTrue(be.growth==1200,"Offline presence of a cold furnace cannot credit heat growth");h.runAfterDelay(21,()->{h.assertTrue(be.growth==1200&&!be.reason(l).isEmpty(),"A real second in a cold habitat does not grow pepper");h.succeed();});}
    @GameTest(template="building_test_empty",batch="botanical",timeoutTicks=30)
    public static void pollenHasOneSecondDebitAndKeepsThreeVisitProgressAcrossRestart(GameTestHelper h){var l=h.getLevel();var p=h.absolutePos(new BlockPos(2,3,2));l.setBlockAndUpdate(p.below(),Blocks.DIRT.defaultBlockState());l.setBlockAndUpdate(p,BotanicalContent.BLOCKS.get("honey_cluster").defaultBlockState());var be=(BotanicalPlantEntity)l.getBlockEntity(p);h.assertTrue(be.pollinateOnce()&&!be.pollinateOnce()&&be.pollinations==1,"Repeated same-second brushing contributes only one visit");var restored=new BotanicalPlantEntity(p,be.getBlockState());restored.load(be.saveWithoutMetadata());h.assertTrue(restored.pollinations==1&&!restored.pollinateOnce(),"Reload retains pollen and same-second cooldown");h.succeed();}
    @GameTest(template="building_test_empty",batch="botanical",timeoutTicks=30)
    public static void twoFrostBottlesAreRequiredAndHarvestLeavesTheRootAlive(GameTestHelper h){var l=h.getLevel();var p=h.absolutePos(new BlockPos(2,3,2));l.setBlockAndUpdate(p.below(),Blocks.DIRT.defaultBlockState());var block=BotanicalContent.BLOCKS.get("frost_chime");l.setBlockAndUpdate(p,block.defaultBlockState().setValue(BotanicalBlock.AGE,3));var be=(BotanicalPlantEntity)l.getBlockEntity(p);be.growth=BotanicalSpecies.FROST_CHIME.firstTicks;var player=AdventureGameTests.player(h);player.getInventory().setItem(0,new ItemStack(Items.GLASS_BOTTLE,1));var hit=new BlockHitResult(Vec3.atCenterOf(p),Direction.UP,p,false);block.use(l.getBlockState(p),l,p,player,InteractionHand.MAIN_HAND,hit);h.assertTrue(be.growth==BotanicalSpecies.FROST_CHIME.firstTicks&&player.getMainHandItem().getCount()==1,"Insufficient containers leave mature plant and bottle intact");player.getInventory().setItem(0,new ItemStack(Items.GLASS_BOTTLE,2));block.use(l.getBlockState(p),l,p,player,InteractionHand.MAIN_HAND,hit);int products=player.getInventory().items.stream().filter(s->s.is(BotanicalContent.PRODUCTS.get("frost_dew"))).mapToInt(ItemStack::getCount).sum();h.assertTrue(products==2&&l.getBlockState(p).is(block)&&l.getBlockState(p).getValue(BotanicalBlock.AGE)==1,"Two real bottles become two dew products and the living root regrows");h.succeed();}
    @GameTest(template="building_test_empty",batch="botanical",timeoutTicks=30)
    public static void starFruitConsumesOneAndRestoresOnlyMissingRealMana(GameTestHelper h){var p=AdventureGameTests.player(h);var magic=MagicStone.getOrNull(p);magic.assignDefaultAffinities(3);magic.setMana(magic.getMaxMana()-20);var fruit=new ItemStack(BotanicalContent.PRODUCTS.get("star_dew_fruit"),2);var result=fruit.finishUsingItem(p.level(),p);h.assertTrue(result.getCount()==1&&magic.getMana()==magic.getMaxMana(),"One fruit restores up to thirty actual mana, capped at maximum");h.assertTrue(fruit.getUseDuration()==16&&p.getCooldowns().isOnCooldown(fruit.getItem()),"Fruit has sixteen-tick consumption and real four-second cooldown");h.succeed();}
    @GameTest(template="building_test_empty",batch="botanical",timeoutTicks=30)
    public static void seedBoxHasFourRealSlotsSixteenPerSpeciesAndFlushesOnEveryMove(GameTestHelper h){var p=AdventureGameTests.player(h);ItemStack box=new ItemStack(BotanicalContent.PRODUCTS.get("rainproof_seed_box"));box.getOrCreateTag().putUUID("FieldContainer",UUID.randomUUID());p.getInventory().setItem(0,box);p.getInventory().setItem(9,new ItemStack(BotanicalContent.SEEDS.get("star_dew"),30));var menu=new PortableFieldMenu(18,p.getInventory(),false,0);menu.quickMoveStack(p,4);h.assertTrue(menu.slots.get(0).getItem().getCount()==16&&p.getInventory().getItem(9).getCount()==14,"Shift transfer respects sixteen-per-species capacity without deleting overflow");h.assertTrue(!menu.slots.get(1).mayPlace(new ItemStack(BotanicalContent.SEEDS.get("star_dew")))&&!menu.accepts(box),"A species cannot use a second slot and nested container is rejected");var reopened=new PortableFieldMenu(19,p.getInventory(),false,0);h.assertTrue(reopened.slots.get(0).getItem().getCount()==16&&box.getTag().getList("FieldContents",10).size()==1,"NBT already contains real sixteen seeds before menu close");h.assertTrue(menu.quickMoveStack(p,31).isEmpty()&&p.getInventory().getItem(0).is(box.getItem()),"Held container is locked while it is open");h.succeed();}
    @GameTest(template="building_test_empty",batch="botanical",timeoutTicks=30)
    public static void archiveFolderRetainsSignedSurveyNbtAndRejectsUnsignedPaper(GameTestHelper h){var p=AdventureGameTests.player(h);var folder=new ItemStack(BotanicalContent.PRODUCTS.get("survey_archive_folder"));folder.getOrCreateTag().putUUID("FieldContainer",UUID.randomUUID());p.getInventory().setItem(0,folder);var page=new ItemStack(BotanicalContent.PRODUCTS.get("stone_rubbing_page"));page.getOrCreateTag().putUUID("Sampler",p.getUUID());page.getOrCreateTag().putInt("Pattern",3);page.getOrCreateTag().putLong("SamplePosition",123456);p.getInventory().setItem(9,page);var menu=new PortableFieldMenu(20,p.getInventory(),true,0);h.assertTrue(!menu.accepts(new ItemStack(Items.PAPER)),"Unsigned paper is not an archived survey");menu.quickMoveStack(p,12);var loaded=new PortableFieldMenu(21,p.getInventory(),true,0);var saved=loaded.slots.get(0).getItem();h.assertTrue(saved.getCount()==1&&saved.getTag().getInt("Pattern")==3&&saved.getTag().getLong("SamplePosition")==123456&&saved.getTag().getUUID("Sampler").equals(p.getUUID()),"Archive stores actual one-page slots and preserves all signed evidence");h.succeed();}
    @GameTest(template="building_test_empty",batch="botanical",timeoutTicks=30)
    public static void oldMapDiscoveryHasTenValidSampleGuaranteeAndKeepsOriginalBlocks(GameTestHelper h){var p=AdventureGameTests.player(h);for(var species:BotanicalSpecies.values()){for(int i=0;i<10&&!p.getPersistentData().getBoolean("TncBotanicalKnown_"+species.id);i++)BotanicalEvents.research(p,species);h.assertTrue(p.getPersistentData().getBoolean("TncBotanicalKnown_"+species.id),"First species seed is guaranteed within ten accepted samples: "+species.id);}h.succeed();}
    @GameTest(template="building_test_empty",batch="botanical_sprites",timeoutTicks=200)
    public static void flowerCreatesThreeRealSpritesReloadDoesNotDuplicateAndDayReturnsProduceDew(GameTestHelper h){var l=h.getLevel();long oldTime=l.getDayTime();l.setDayTime(14000);var fixture=h.absolutePos(new BlockPos(2,3,2));var p=new BlockPos(fixture.getX(),200,fixture.getZ());for(int x=-1;x<=1;x++)for(int z=-1;z<=1;z++){l.setChunkForced((p.getX()>>4)+x,(p.getZ()>>4)+z,true);l.getChunk((p.getX()>>4)+x,(p.getZ()>>4)+z);}l.setBlockAndUpdate(p.below(),Blocks.DIRT.defaultBlockState());l.setBlockAndUpdate(p,BotanicalContent.BLOCKS.get("star_rest").defaultBlockState().setValue(BotanicalBlock.AGE,3));var be=(BotanicalPlantEntity)l.getBlockEntity(p);be.growth=BotanicalSpecies.STAR_REST.firstTicks;
        h.runAfterDelay(82,()->{try{int count=l.getEntitiesOfClass(BotanicalSprite.class,new AABB(p).inflate(7),e->be.motherId.equals(e.mother)).size();h.assertTrue(count==3&&be.spriteIds.size()==3,"Mature flower creates three independently registered saved entities; count="+count+", reason="+be.reason(l)+", day="+l.isDay()+", growth="+be.growth+", lastTick="+be.lastActiveTick+", now="+l.getGameTime()+", ticking="+l.isPositionEntityTicking(p)+", sameEntity="+(l.getBlockEntity(p)==be)+", removed="+be.isRemoved()+", status="+l.getChunkAt(p).getFullStatus()+", entitiesLoaded="+l.areEntitiesLoaded(net.minecraft.world.level.ChunkPos.asLong(p))+", valid="+be.getType().isValid(l.getBlockState(p)));be.load(be.saveWithoutMetadata());be.onLoad();}catch(Throwable error){l.setDayTime(oldTime);throw error;}});
        h.runAfterDelay(103,()->{try{h.assertTrue(l.getEntitiesOfClass(BotanicalSprite.class,new AABB(p).inflate(7),e->be.motherId.equals(e.mother)).size()==3,"Repeated root load does not create additional sprites");l.setDayTime(1000);}catch(Throwable error){l.setDayTime(oldTime);throw error;}});
        h.runAfterDelay(135,()->{try{h.assertTrue(be.ready&&Integer.bitCount(be.returns)>=2&&l.getEntitiesOfClass(BotanicalSprite.class,new AABB(p).inflate(7),e->be.motherId.equals(e.mother)).isEmpty(),"Real daylight return removes entities and unlocks one saved dew harvest");h.succeed();}finally{be.removeSprites(l);l.setDayTime(oldTime);for(int x=-1;x<=1;x++)for(int z=-1;z<=1;z++)l.setChunkForced((p.getX()>>4)+x,(p.getZ()>>4)+z,false);}});
    }
}
